import type { ChallengeDefinition } from "../../challenge-schema";

/** Accordions (spec category #12). All variants share the `accordion` engine component. */
export const accordionsChallenges: ChallengeDefinition[] = [
  {
    id: "ACCORDION-001",
    title: "Single-Open FAQ Accordion",
    categoryId: "accordions",
    component: "accordion",
    variant: "single-open",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/faq-5",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 5-item FAQ accordion where opening one item automatically closes any other open item.",
      dataNeeded: "None.",
      action: "Open \"How do refunds work?\", then open \"What is your SLA?\".",
      expectedResult: "Only the most recently opened item is expanded at any time.",
      validationPoints: ["Exactly one panel is expanded after any click", "Opening a second item collapses the first automatically"],
      automationConcepts: ["aria-expanded assertion", "Mutually-exclusive panel-state verification"],
    },
    validation: [{ kind: "equals", field: "openPanel", expected: "What is your SLA?" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "ACCORDION-002",
    title: "Multi-Open Policy Accordion with Nested Table",
    categoryId: "accordions",
    component: "accordion",
    variant: "multi-open-nested",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/policies-3",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 3-section policy accordion allows multiple sections open simultaneously; one section contains a nested pricing table.",
      dataNeeded: "None.",
      action: "Open all 3 sections at once, then read a value from the nested table inside \"Pricing Tiers\".",
      expectedResult: "All 3 sections remain expanded simultaneously; the nested table is queryable while its parent section is open.",
      validationPoints: ["All 3 sections report expanded=true simultaneously", "Nested table row values are only accessible while the parent panel is expanded"],
      automationConcepts: ["Independent (non-exclusive) panel state", "Locating elements nested inside collapsible containers"],
    },
    validation: [{ kind: "equals", field: "expandedCount", expected: 3 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
