import type { ChallengeDefinition } from "../../challenge-schema";

/** Ajax / Asynchronous Elements (spec category #25). All variants share the `dynamic-dom` engine component. */
export const ajaxAsyncChallenges: ChallengeDefinition[] = [
  {
    id: "AJAX-001",
    title: "Configurable-Delay API (1s / 3s / 5s)",
    categoryId: "ajax-async",
    component: "dynamic-dom",
    variant: "configurable-delay-api",
    behavior: ["api", "delayed"],
    environment: ["none"],
    dataSource: "api/lab-delay",
    difficulty: "medium",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Choosing a delay (1s/3s/5s) then clicking \"Load\" calls `GET /api/lab/delay/:ms` and renders the result only once that exact delay elapses.",
      dataNeeded: "One of: 1000, 3000, 5000 (ms).",
      action: "Select \"5s\" and click Load; do not assert on the result until it actually appears.",
      expectedResult: "Content appears only after ~5 seconds, not sooner, with a visible loading indicator throughout.",
      validationPoints: ["Result is absent for the full delay duration", "Result text equals \"Loaded after 5000ms\" once it appears"],
      automationConcepts: ["Explicit/conditional waits vs fixed sleeps", "Avoiding false positives from asserting too early"],
    },
    validation: [{ kind: "equals", field: "loadedLabel", expected: "Loaded after 5000ms" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "AJAX-002",
    title: "Flaky Endpoint That Succeeds After 2 Retries",
    categoryId: "ajax-async",
    component: "dynamic-dom",
    variant: "flaky-retry-api",
    behavior: ["api", "retry", "failure"],
    environment: ["none"],
    dataSource: "api/lab-flaky",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "`GET /api/lab/flaky` deterministically fails (500) on the first 2 calls per session and succeeds on the 3rd, simulating a transient backend issue.",
      dataNeeded: "None.",
      action: "Click \"Fetch account balance\" and click \"Retry\" after each failure until it succeeds.",
      expectedResult: "The first two attempts show an error with a Retry button; the third attempt succeeds and shows the balance.",
      validationPoints: ["attemptCount equals 3 when success is finally shown", "Balance value equals \"$12,450.00\" only on the successful attempt"],
      automationConcepts: ["Retry-loop test design", "Distinguishing transient failures from permanent ones", "Bounded-retry assertions (not infinite retry)"],
    },
    validation: [
      { kind: "equals", field: "attemptCount", expected: 3 },
      { kind: "equals", field: "accountBalance", expected: "$12,450.00" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "AJAX-003",
    title: "Empty API Response State",
    categoryId: "ajax-async",
    component: "dynamic-dom",
    variant: "empty-api-response",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-empty",
    difficulty: "easy",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "`GET /api/lab/empty-response` always returns `{ data: [] }`; the UI must render a real empty state, not a blank area or an error.",
      dataNeeded: "None.",
      action: "Click \"Load notifications\".",
      expectedResult: "An explicit \"No notifications yet\" empty state renders \u2014 never a blank panel and never treated as an error.",
      validationPoints: ["emptyStateShown is true after loading", "No error message is shown for a legitimately empty (not failed) response"],
      automationConcepts: ["Distinguishing empty-but-successful responses from errors", "Asserting on explicit empty-state content"],
    },
    validation: [{ kind: "equals", field: "emptyStateShown", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
];
