import type { ChallengeDefinition } from "../../challenge-schema";

/** Alerts & Notifications (spec category #14). All variants share the `toast` engine component. */
export const alertsNotificationsChallenges: ChallengeDefinition[] = [
  {
    id: "ALERT-001",
    title: "Native Confirm Dialog — Discard Changes",
    categoryId: "alerts-notifications",
    component: "toast",
    variant: "native-confirm",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Navigating away from an edited form triggers the browser's native `window.confirm(\"Discard changes?\")` dialog.",
      dataNeeded: "None.",
      action: "Type text into the field, then click \"Leave page\"; accept the dialog once, then repeat and dismiss it.",
      expectedResult: "Accepting navigates away; dismissing keeps you on the form with the typed text intact.",
      validationPoints: ["Accepting the dialog changes the route", "Dismissing the dialog leaves the field value unchanged"],
      automationConcepts: ["Native `dialog` event handling (accept/dismiss)", "Framework-specific dialog auto-handling differences"],
      edgeCases: ["Real browsers block scripted control of some native dialogs in certain contexts; this challenge uses the standard, automatable `confirm()` API."],
    },
    validation: [{ kind: "equals", field: "leftPage", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "ALERT-002",
    title: "Stacked Toast Queue with Auto-Dismiss",
    categoryId: "alerts-notifications",
    component: "toast",
    variant: "stacked-toast-queue",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Triggering 3 background jobs in quick succession queues 3 stacked toasts, each auto-dismissing after 4 seconds independently.",
      dataNeeded: "None.",
      action: "Click \"Run job\" 3 times quickly, then wait.",
      expectedResult: "3 toasts stack visibly; each disappears independently ~4s after it appeared (not all at once).",
      validationPoints: ["Toast count equals 3 immediately after 3 clicks", "Toast count returns to 0 after waiting, without a manual dismiss action"],
      automationConcepts: ["Transient-element polling", "Independent per-element timers vs waiting for a fixed instant"],
    },
    validation: [{ kind: "equals", field: "toastCount", expected: 3 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
