import type { ChallengeDefinition } from "../../challenge-schema";

/** API-Driven UI (spec category #32). Additional dedicated challenges beyond the flagship dependent dropdown. */
export const apiDrivenUiChallenges: ChallengeDefinition[] = [
  {
    id: "APIUI-001",
    title: "Category-Filtered Product Grid",
    categoryId: "api-driven-ui",
    component: "api-panel",
    variant: "category-filtered-grid",
    behavior: ["api", "dependent"],
    environment: ["none"],
    dataSource: "api/lab-products",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Loads categories from `GET /api/lab/categories`, then loads only matching products from `GET /api/lab/products?category=X` when one is selected.",
      dataNeeded: "One category selection, e.g. \"Furniture\".",
      action: "Select \"Furniture\" from the category dropdown.",
      expectedResult: "The product grid updates to show only the 2 seeded Furniture products (Standing Desk, Ergo Chair).",
      validationPoints: ["visibleProductCount equals 2 after selecting Furniture", "Products from other categories are not shown"],
      automationConcepts: ["Two-stage API dependency (categories \u2192 filtered products)", "Query-parameter-driven UI refresh"],
    },
    validation: [{ kind: "equals", field: "visibleProductCount", expected: 2 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "APIUI-002",
    title: "Dashboard Widget — Loading, Error, Retry, Empty States",
    categoryId: "api-driven-ui",
    component: "api-panel",
    variant: "dashboard-widget-states",
    behavior: ["api", "failure", "retry"],
    environment: ["none"],
    dataSource: "api/lab-failure",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A dashboard widget fetches a report; the first attempt in a fresh session always fails (500), and retrying succeeds \u2014 modeling a realistic \"widget failed to load, tap to retry\" pattern.",
      dataNeeded: "None.",
      action: "Load the widget (observe the error state), then click \"Retry\".",
      expectedResult: "First load shows an error state with a Retry action; retrying shows the successful report content.",
      validationPoints: ["Widget shows an explicit error state (not a blank panel) on first failure", "Widget shows successful content after Retry"],
      automationConcepts: ["Loading \u2192 error \u2192 retry \u2192 success state machine testing", "Widget-level (not full-page) error boundaries"],
    },
    validation: [{ kind: "equals", field: "widgetStatus", expected: "loaded" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
