import type { ChallengeDefinition } from "../../challenge-schema";

/** Authentication (spec category #33) — basic login/session flows for v1. */
export const authenticationChallenges: ChallengeDefinition[] = [
  {
    id: "AUTH-001",
    title: "Login — Valid and Invalid Credentials",
    categoryId: "authentication",
    component: "auth-panel",
    variant: "login-basic",
    behavior: ["api", "validated-on-submit"],
    environment: ["none"],
    dataSource: "api/auth-login",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Standard enterprise login form backed by `POST /api/auth/login`.",
      dataNeeded: "Seeded account: learner@qaplatform.dev / Learner123!",
      action: "Submit with a wrong password (expect error), then submit with the seeded valid credentials.",
      expectedResult: "Invalid login shows \"Invalid email or password\"; valid login redirects to the Dashboard with the user's name in the header.",
      validationPoints: ["Error message shown for invalid credentials without navigating away", "Successful login sets an auth session and redirects"],
      automationConcepts: ["Form submission", "API status-code assertion", "Post-login redirect assertion", "Session/cookie presence check"],
      edgeCases: ["Case sensitivity of email should not affect login (emails treated case-insensitively)"],
    },
    validation: [{ kind: "equals", field: "authStatus", expected: "authenticated" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "AUTH-002",
    title: "Account Lockout After 3 Failed Attempts",
    categoryId: "authentication",
    component: "auth-panel",
    variant: "account-lockout",
    behavior: ["api", "validated-on-submit"],
    environment: ["none"],
    dataSource: "api/auth-login",
    difficulty: "medium",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "The seeded account \"locked_demo@qaplatform.dev\" locks itself after 3 consecutive failed password attempts within this session.",
      dataNeeded: "Seeded account: locked_demo@qaplatform.dev with any wrong password 3 times.",
      action: "Submit an incorrect password 3 times in a row.",
      expectedResult: "After the 3rd failed attempt, the form shows \"Account locked. Try again in 60 seconds.\" and the submit button disables.",
      validationPoints: ["Attempt counter increments per failed submit", "Lockout message appears exactly after the 3rd failure", "Submit is disabled while locked"],
      automationConcepts: ["Stateful sequential API calls", "Rate-limit-style assertion", "Disabled-state after threshold"],
    },
    validation: [{ kind: "equals", field: "lockoutState", expected: "locked" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "AUTH-003",
    title: "MFA / OTP Login Flow",
    categoryId: "authentication",
    component: "auth-panel",
    variant: "mfa-otp-login",
    behavior: ["api", "validated-on-submit"],
    environment: ["none"],
    dataSource: "api/auth-login",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "The seeded account \"mfa_demo@qaplatform.dev\" requires a 6-digit one-time code after password verification, mirroring a real MFA-enabled login.",
      dataNeeded: "Seeded account: mfa_demo@qaplatform.dev / Learner123!.",
      action: "Submit the password; the code appears in a test-only response field (`otp`) instead of an SMS/email \u2014 copy it into the verification field and submit.",
      expectedResult: "Password step succeeds and reveals the OTP step; entering the correct code completes login and issues a session.",
      validationPoints: ["mfaStep equals \"otp\" immediately after password submission", "authStatus equals \"authenticated\" only after the correct OTP is submitted", "An incorrect OTP is rejected without granting a session"],
      automationConcepts: ["Multi-step auth flow testing", "Reading test-only backdoor fields instead of real SMS/email (a common real-world MFA test pattern)", "Negative-path OTP rejection"],
      edgeCases: ["The OTP expires after 60 seconds server-side \u2014 useful for testing expired-code handling."],
    },
    validation: [{ kind: "equals", field: "authStatus", expected: "authenticated" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "AUTH-004",
    title: "Role-Based Access Control — Admin-Only Report",
    categoryId: "authentication",
    component: "auth-panel",
    variant: "role-based-access",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-admin-report",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "`GET /api/lab/admin-report` is protected by real role-based access control: 401 if not signed in, 403 if signed in with the wrong role, 200 only for an 'admin' session.",
      dataNeeded: "Seeded accounts: learner@qaplatform.dev (learner), manager@qaplatform.dev (manager), admin@qaplatform.dev (admin).",
      action: "Sign in as \"learner\" and request the report (expect 403), then sign in as \"admin\" and request it again (expect 200).",
      expectedResult: "Non-admin roles are rejected with 403 Forbidden; only the admin role receives the report content.",
      validationPoints: ["Learner/manager role request returns 403", "Admin role request returns 200 with report content"],
      automationConcepts: ["Role-based access control (RBAC) testing", "Testing the SAME endpoint across multiple user roles", "401 vs 403 distinction (unauthenticated vs unauthorized)"],
    },
    validation: [{ kind: "equals", field: "adminReportStatus", expected: 200 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "AUTH-005",
    title: "Session Timeout — Expired Session Redirects to Login",
    categoryId: "authentication",
    component: "auth-panel",
    variant: "session-timeout",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/auth-me",
    difficulty: "medium",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Simulates an expired session cookie by clearing it locally, then calling `GET /api/auth/me` \u2014 the real session-validity check the app relies on everywhere.",
      dataNeeded: "None.",
      action: "Sign in, confirm the session is valid, click \"Simulate session expiry\", then check the session again.",
      expectedResult: "Before expiry, `/api/auth/me` returns the current user (200); after simulated expiry, it returns 401 and the app should treat this as \"please sign in again\".",
      validationPoints: ["Session check returns 200 while valid", "Session check returns 401 after expiry, without the app crashing or showing stale user data"],
      automationConcepts: ["Session-expiry simulation", "Verifying graceful degradation on auth failure", "401-triggered re-authentication flow"],
    },
    validation: [{ kind: "equals", field: "sessionStatusAfterExpiry", expected: 401 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
