import type { ChallengeDefinition } from "../../challenge-schema";

/**
 * Basic UI Actions (spec category #1). All challenges share ONE
 * `action-surface` engine component; only the `variant` differs.
 */
export const basicUiActionsChallenges: ChallengeDefinition[] = [
  {
    id: "BASIC-001",
    title: "Click to Increment Ticket Counter",
    categoryId: "basic-ui-actions",
    component: "action-surface",
    variant: "click-counter",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A stable button that increments an open-ticket counter each time it is clicked, mirroring a support-desk 'New Ticket' action.",
      dataNeeded: "None. Purely a click counter.",
      action: "Click the \"New Ticket\" button 3 times.",
      expectedResult: "The \"Open Tickets\" counter reads 3 and the button remains enabled.",
      validationPoints: ["Counter text equals \"3\"", "Button stays enabled after each click"],
      automationConcepts: ["Locator", "Click action", "Text assertion", "Idempotent re-click"],
      edgeCases: ["Rapid double-click should still register exactly one increment per click"],
    },
    validation: [{ kind: "equals", field: "counter", expected: 3 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "BASIC-002",
    title: "Double-Click to Archive Row",
    categoryId: "basic-ui-actions",
    component: "action-surface",
    variant: "double-click",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Simulates an enterprise table row that archives itself on double-click (a common power-user shortcut).",
      dataNeeded: "None.",
      action: "Double-click the row labeled \"INV-2044\".",
      expectedResult: "The row's status badge changes to \"Archived\".",
      validationPoints: ["Row status attribute equals \"archived\"", "Single click must NOT archive the row"],
      automationConcepts: ["Double-click action", "Attribute assertion", "Negative assertion (single click has no effect)"],
    },
    validation: [{ kind: "equals", field: "rowStatus", expected: "archived" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "BASIC-003",
    title: "Right-Click Context Menu on Order",
    categoryId: "basic-ui-actions",
    component: "action-surface",
    variant: "right-click-context-menu",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Right-clicking an order row opens a custom context menu with actions (Duplicate, Cancel, Export).",
      dataNeeded: "None.",
      action: "Right-click order \"ORD-5521\", then click \"Duplicate\" in the context menu.",
      expectedResult: "A new order row \"ORD-5521-COPY\" appears in the list.",
      validationPoints: ["Context menu becomes visible on right-click", "New row with suffix -COPY exists after choosing Duplicate"],
      automationConcepts: ["Context-click action", "Dynamically appearing menu", "Element existence assertion"],
      edgeCases: ["Clicking elsewhere should close the menu without side effects"],
    },
    validation: [{ kind: "contains", field: "orderIds", expected: "ORD-5521-COPY" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "BASIC-004",
    title: "Hover to Reveal Row Actions",
    categoryId: "basic-ui-actions",
    component: "action-surface",
    variant: "hover-reveal",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Row-level action icons (Edit/Delete) are hidden until the row is hovered — a common enterprise table pattern.",
      dataNeeded: "None.",
      action: "Hover over the \"Employee: Priya Sharma\" row.",
      expectedResult: "Edit and Delete icons become visible for that row only.",
      validationPoints: ["Icons have `visibility: visible` / are present only on the hovered row", "Icons hide again on mouse-leave"],
      automationConcepts: ["Hover action", "CSS visibility state assertion", "Mouse-leave behavior"],
    },
    validation: [{ kind: "truthy", field: "actionsVisible" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "BASIC-005",
    title: "Keyboard Focus / Blur on Search Field",
    categoryId: "basic-ui-actions",
    component: "action-surface",
    variant: "focus-blur-tracker",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Tracks focus/blur transitions on a global search field, showing a live status badge (\"Focused\" / \"Blurred\").",
      dataNeeded: "None.",
      action: "Tab into the search field, then Tab out (or click elsewhere).",
      expectedResult: "Status badge reads \"Focused\" while active, then \"Blurred\" after leaving.",
      validationPoints: ["Status equals \"focused\" immediately after focus", "Status equals \"blurred\" after blur"],
      automationConcepts: ["Keyboard navigation (Tab)", "Focus/blur event assertions", "Live status text polling"],
    },
    validation: [{ kind: "equals", field: "focusState", expected: "blurred" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "BASIC-006",
    title: "Enable / Disable Approve Button",
    categoryId: "basic-ui-actions",
    component: "action-surface",
    variant: "enable-disable-toggle",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An \"Approve Expense\" button is disabled until the \"I reviewed the receipt\" checkbox is checked.",
      dataNeeded: "Checkbox state (boolean).",
      action: "Check the \"I reviewed the receipt\" checkbox, then click \"Approve Expense\".",
      expectedResult: "Button becomes enabled after the checkbox is checked, and clicking it shows an \"Approved\" badge.",
      validationPoints: ["Button `disabled` attribute is false only after checkbox is checked", "Approval badge appears after click"],
      automationConcepts: ["Disabled-state assertion", "Conditional enablement", "Click after state change"],
    },
    validation: [{ kind: "equals", field: "approvalState", expected: "approved" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
];
