import type { ChallengeDefinition } from "../../challenge-schema";

/** Browser Storage (spec category #35). All variants share the `storage-panel` engine component. */
export const browserStorageChallenges: ChallengeDefinition[] = [
  {
    id: "STORAGE-001",
    title: "LocalStorage Preference Survives Reload",
    categoryId: "browser-storage",
    component: "storage-panel",
    variant: "localstorage-persistence",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Saves a \"compact density\" UI preference to `localStorage` under key `qalab_density`, which must survive a simulated reload.",
      dataNeeded: "One of \"comfortable\" or \"compact\".",
      action: "Select \"Compact\", click \"Save preference\", then click \"Simulate reload\".",
      expectedResult: "After the simulated reload, the density selector still shows \"Compact\", read directly from localStorage.",
      validationPoints: ["localStorage.getItem('qalab_density') equals \"compact\"", "UI reflects the persisted value after reload, not a default"],
      automationConcepts: ["Reading/writing localStorage directly in tests", "Persistence-across-reload verification"],
    },
    validation: [{ kind: "equals", field: "densityPreference", expected: "compact" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "STORAGE-002",
    title: "SessionStorage Cart Cleared on \"New Session\"",
    categoryId: "browser-storage",
    component: "storage-panel",
    variant: "sessionstorage-cart",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Adds items to a cart stored in `sessionStorage` (key `qalab_cart`); a \"Simulate new session\" button clears sessionStorage the way a real new tab/session would.",
      dataNeeded: "None.",
      action: "Add 2 items to the cart, confirm the count, then click \"Simulate new session\".",
      expectedResult: "Cart count is 2 before simulating a new session, and 0 immediately after.",
      validationPoints: ["sessionStorage-backed cart count equals 2 after adding two items", "Cart count equals 0 after the new-session simulation, distinct from localStorage which would persist"],
      automationConcepts: ["sessionStorage vs localStorage lifecycle differences", "Simulating a fresh session in tests"],
    },
    validation: [{ kind: "equals", field: "cartCount", expected: 0 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
