import type { ChallengeDefinition } from "../../challenge-schema";

/** Browser Windows & Tabs (spec category #27). All variants share the `window-lab` engine component. */
export const browserWindowsTabsChallenges: ChallengeDefinition[] = [
  {
    id: "WINDOW-001",
    title: "Parent-Child Window — Process Transaction",
    categoryId: "browser-windows-tabs",
    component: "window-lab",
    variant: "parent-child-transaction",
    behavior: ["dynamic"],
    environment: ["new-tab"],
    dataSource: "static/none",
    difficulty: "expert",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Process Transaction\" opens a second tab. Approving the transaction there and closing it must update the ORIGINAL tab's status.",
      dataNeeded: "None.",
      action: "Click \"Process Transaction\", switch to the new tab, click \"Approve\", close that tab, then return to the original tab.",
      expectedResult: "The original tab now shows \"Transaction Status: COMPLETED\" without any manual refresh.",
      validationPoints: ["Parent page status updates to COMPLETED only after approval in the child tab", "Status remains PENDING if the child tab is closed without approving"],
      automationConcepts: ["Window/tab handle switching", "Waiting for cross-tab state propagation", "Returning focus to the original window/page object"],
    },
    validation: [{ kind: "equals", field: "transactionStatus", expected: "COMPLETED" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
  {
    id: "WINDOW-002",
    title: "Open Three Tabs and Track Count",
    categoryId: "browser-windows-tabs",
    component: "window-lab",
    variant: "multi-tab-tracker",
    behavior: ["dynamic"],
    environment: ["new-tab"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Each click on \"Open Report Tab\" opens a new tab and registers itself with the opener via BroadcastChannel; the opener shows a live count of currently-open report tabs.",
      dataNeeded: "None.",
      action: "Open 3 report tabs, then close 1 of them.",
      expectedResult: "Open-tab count reads 3 after opening all three, then 2 after closing one.",
      validationPoints: ["openTabCount equals 3 after opening three tabs", "openTabCount equals 2 after closing one"],
      automationConcepts: ["Tracking multiple window handles", "Cross-tab messaging (BroadcastChannel)", "Cleanup/unregister-on-close verification"],
    },
    validation: [{ kind: "range", field: "openTabCount", min: 0, max: 3 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
