import type { ChallengeDefinition } from "../../challenge-schema";

/** Buttons & Click Behaviors (spec category #4). Shares the `button` engine component. */
export const buttonsChallenges: ChallengeDefinition[] = [
  {
    id: "BUTTON-001",
    title: "Standard Button Triggers Toast",
    categoryId: "buttons",
    component: "button",
    variant: "trigger-toast",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Send Reminder\" fires an application toast notification.",
      dataNeeded: "None.",
      action: "Click \"Send Reminder\".",
      expectedResult: "A success toast reading \"Reminder sent\" appears and auto-dismisses after 4 seconds.",
      validationPoints: ["Toast text equals \"Reminder sent\"", "Toast disappears without user action within ~4s"],
      automationConcepts: ["Click action", "Transient element assertion", "Auto-dismiss timing"],
    },
    validation: [{ kind: "equals", field: "lastToast", expected: "Reminder sent" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "BUTTON-002",
    title: "Button Enabled Only After Required Input",
    categoryId: "buttons",
    component: "button",
    variant: "enabled-after-input",
    behavior: ["validated-live"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Submit Expense\" stays disabled until an amount greater than 0 is entered.",
      dataNeeded: "Number > 0, e.g. 1250.",
      action: "Try clicking Submit while empty (no effect), enter 1250, then click Submit.",
      expectedResult: "Button is disabled while amount is empty/zero and becomes enabled and clickable once a positive amount is entered.",
      validationPoints: ["Button `disabled` attribute reflects amount validity at every step", "Submit only succeeds with amount > 0"],
      automationConcepts: ["Conditional enablement", "Disabled-state polling", "Guarded click"],
    },
    validation: [{ kind: "range", field: "amount", min: 1 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "BUTTON-003",
    title: "Button Triggering API Call with Loading Spinner",
    categoryId: "buttons",
    component: "button",
    variant: "api-triggered",
    behavior: ["api", "delayed"],
    environment: ["none"],
    dataSource: "api/process-payment",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Process Payment\" calls a backend endpoint that takes ~1.2s, showing a spinner and disabling the button meanwhile.",
      dataNeeded: "None — payment payload is pre-filled.",
      action: "Click \"Process Payment\" and wait for the result.",
      expectedResult: "Button shows a spinner and is disabled during the call; on success it shows \"Payment Approved\".",
      validationPoints: ["Button is disabled for the full duration of the request", "Final state text equals \"Payment Approved\""],
      automationConcepts: ["Network wait", "Loading-state assertion", "Auto-wait for post-API DOM update"],
      edgeCases: ["Use `?mode=random` on the endpoint to occasionally exercise the \"Payment Declined\" failure path."],
    },
    validation: [{ kind: "equals", field: "paymentStatus", expected: "Payment Approved" }],
    mode: { deterministic: true, randomAvailable: true },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "BUTTON-004",
    title: "Confirmation Button for Destructive Action",
    categoryId: "buttons",
    component: "button",
    variant: "confirm-destructive",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Delete Project\" opens a confirmation modal before performing the destructive action.",
      dataNeeded: "None.",
      action: "Click \"Delete Project\", then click \"Cancel\" (project remains); click \"Delete Project\" again, then confirm \"Yes, delete\".",
      expectedResult: "Cancel leaves the project in the list; confirming removes it and shows a success toast.",
      validationPoints: ["Project remains after Cancel", "Project is removed only after explicit confirmation"],
      automationConcepts: ["Modal locator scoping", "Two-step destructive-action pattern", "Negative-then-positive assertion"],
    },
    validation: [{ kind: "equals", field: "projectDeleted", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "BUTTON-005",
    title: "Prevent Double Submit",
    categoryId: "buttons",
    component: "button",
    variant: "prevent-double-submit",
    behavior: ["api", "delayed"],
    environment: ["none"],
    dataSource: "api/create-order",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Place Order\" disables itself immediately on first click while the create-order request (~600ms) is in flight, preventing duplicate orders from rapid re-clicks.",
      dataNeeded: "None.",
      action: "Click \"Place Order\" rapidly multiple times in quick succession.",
      expectedResult: "Exactly one order is created regardless of how many times the button was clicked during the in-flight window.",
      validationPoints: ["`ordersCreated` equals 1 even after 5 rapid clicks", "Button is disabled between first click and response"],
      automationConcepts: ["Race-condition testing", "Disabled-state assertion under rapid interaction", "Idempotency verification"],
    },
    validation: [{ kind: "equals", field: "ordersCreated", expected: 1 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "BUTTON-006",
    title: "Full-Page Blocking Loader During Submission",
    categoryId: "buttons",
    component: "button",
    variant: "full-page-blocking-loader",
    behavior: ["delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Submit Large Report\" covers the ENTIRE page with a blocking spinner overlay for ~2.5s \u2014 no other element on the page (not just the button) can be interacted with until it disappears.",
      dataNeeded: "None.",
      action: "Click \"Submit Large Report\", then immediately try clicking the unrelated \"Decoy Button\" elsewhere on the page while the overlay is showing, then wait for it to finish.",
      expectedResult: "Clicks on the decoy button during the overlay are swallowed (do not register); once the overlay disappears, the decoy button works normally and the report shows submitted.",
      validationPoints: ["decoyClicksDuringLoad equals 0", "reportSubmitted equals true only after the overlay fully disappears"],
      automationConcepts: ["Full-page interaction-blocking overlay verification", "Asserting an element's clicks are intercepted/swallowed while covered", "Waiting for an overlay to fully detach before interacting with the page again"],
      edgeCases: ["A test that clicks through the overlay without waiting is exactly the kind of flaky test this challenge is designed to catch."],
    },
    validation: [
      { kind: "equals", field: "decoyClicksDuringLoad", expected: 0 },
      { kind: "equals", field: "reportSubmitted", expected: true },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
