import type { ChallengeDefinition } from "../../challenge-schema";

/** Cookies (spec category #34). All variants share the `cookie-panel` engine component. */
export const cookiesChallenges: ChallengeDefinition[] = [
  {
    id: "COOKIE-001",
    title: "Set, Read, and Clear a Preference Cookie",
    categoryId: "cookies",
    component: "cookie-panel",
    variant: "set-read-clear",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Sets a non-httpOnly `qalab_theme` cookie via a Dark/Light toggle, so both the UI and the browser's own cookie store reflect the same value.",
      dataNeeded: "One of \"dark\" or \"light\".",
      action: "Select \"Dark\", click \"Read Cookie\" to confirm, then click \"Clear Cookie\".",
      expectedResult: "Reading shows `qalab_theme=dark`; after clearing, the cookie no longer appears in `document.cookie`.",
      validationPoints: ["document.cookie contains \"qalab_theme=dark\" after setting", "document.cookie no longer contains \"qalab_theme\" after clearing"],
      automationConcepts: ["Direct cookie inspection/manipulation (framework cookie APIs)", "Asserting absence after deletion"],
    },
    validation: [{ kind: "equals", field: "themeCookieValue", expected: "" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "COOKIE-002",
    title: "Expiring \"Remember Me\" Cookie",
    categoryId: "cookies",
    component: "cookie-panel",
    variant: "expiring-cookie",
    behavior: ["delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Checking \"Remember me\" sets a `qalab_remember` cookie with a 5-second expiry, so it demonstrably disappears on its own without any manual deletion.",
      dataNeeded: "None.",
      action: "Check \"Remember me\", confirm the cookie exists immediately, then wait 6 seconds and check again.",
      expectedResult: "Cookie is present right after checking the box and absent once the 5-second expiry passes.",
      validationPoints: ["Cookie present immediately after setting", "Cookie absent after waiting past its expiry, with no user action required"],
      automationConcepts: ["Time-based cookie expiry verification", "Polling-with-wait vs immediate assertion"],
    },
    validation: [{ kind: "equals", field: "rememberCookieExpired", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
