import type { ChallengeDefinition } from "../../challenge-schema";

/** Date & Time Controls (spec category #16). All variants share the `date-time` engine component. */
export const dateTimeChallenges: ChallengeDefinition[] = [
  {
    id: "DATE-001",
    title: "Date Picker with Min/Max Restriction",
    categoryId: "date-time",
    component: "date-time",
    variant: "min-max-restriction",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Schedule Maintenance\" date field only accepts dates within the next 30 days (no past dates, nothing beyond +30 days).",
      dataNeeded: "A date within the allowed window.",
      action: "Try selecting yesterday's date (rejected), then select a date 10 days from today (accepted).",
      expectedResult: "Out-of-range dates are rejected with an inline error; in-range dates are accepted and shown formatted as YYYY-MM-DD.",
      validationPoints: ["Selecting a past date shows \"Date must be between today and +30 days\"", "Selecting a valid date sets the field value with no error"],
      automationConcepts: ["Native <input type=\"date\"> value assertions", "Min/max attribute-based boundary testing", "Date arithmetic in test data"],
    },
    validation: [{ kind: "matches", field: "scheduledDate", pattern: "^\\d{4}-\\d{2}-\\d{2}$" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DATE-002",
    title: "Check-In / Check-Out Date Range Picker",
    categoryId: "date-time",
    component: "date-time",
    variant: "date-range-picker",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A hotel-booking style range picker where Check-out must always be after Check-in; picking an earlier check-out auto-adjusts it.",
      dataNeeded: "Two dates, check-in before check-out.",
      action: "Set Check-in to a date, then try setting Check-out to an earlier date.",
      expectedResult: "Check-out cannot be before Check-in; the UI either blocks the selection or snaps Check-out to Check-in + 1 day.",
      validationPoints: ["nights (check-out minus check-in) is always >= 1", "Check-out field's min attribute updates to match the chosen check-in"],
      automationConcepts: ["Cross-field date validation", "Dynamic min/max attribute assertions", "Derived-value (nights) calculation check"],
    },
    validation: [{ kind: "range", field: "nights", min: 1 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "DATE-003",
    title: "Time Picker with Dynamic Available Slots",
    categoryId: "date-time",
    component: "date-time",
    variant: "dynamic-time-slots",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/appointment-slots",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An appointment time picker disables slots that are already booked (09:00 and 14:00 are pre-booked and shown disabled).",
      dataNeeded: "One available time slot.",
      action: "Try clicking the disabled \"09:00\" slot, then select the available \"10:30\" slot.",
      expectedResult: "Disabled slots cannot be selected; selecting an available slot highlights it and confirms the appointment.",
      validationPoints: ["Disabled slot remains unselected after attempted click", "Selected time equals \"10:30\""],
      automationConcepts: ["Disabled-option negative testing", "Dynamic list rendering based on seeded availability data"],
    },
    validation: [{ kind: "equals", field: "selectedTimeSlot", expected: "10:30" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DATE-004",
    title: "Flexible Date Entry — Multiple Accepted Formats",
    categoryId: "date-time",
    component: "date-time",
    variant: "multi-format-date-input",
    behavior: ["validated-on-blur"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A free-text \"Date of Birth\" field accepts several real-world date formats \u2014 `dd-mm-yyyy`, `MM-DD-YYYY`, and long form like `06 July 1990` \u2014 and normalizes whichever is typed to ISO `yyyy-mm-dd` for display.",
      dataNeeded: "A date in any of the three supported formats, e.g. \"06-07-1990\" or \"July 6, 1990\".",
      action: "Type \"06-07-1990\" and blur (ambiguous day/month is resolved as dd-mm-yyyy), then clear it and type \"06 July 1990\" and blur.",
      expectedResult: "Both inputs normalize to the same ISO date `1990-07-06`; an unrecognized format shows \"Unrecognized date format\" instead of silently accepting garbage.",
      validationPoints: ["Normalized value equals \"1990-07-06\" for both supported input styles", "An invalid/unsupported format is rejected with a visible error, not silently coerced"],
      automationConcepts: ["Multi-format input parsing verification", "Locale/format-ambiguity awareness (dd-mm vs mm-dd)", "Negative-case format-rejection testing"],
      edgeCases: ["\"13-02-1990\" is unambiguous (no 13th month) and must parse as dd-mm-yyyy even though the field also nominally accepts MM-DD-YYYY."],
    },
    validation: [{ kind: "equals", field: "normalizedDate", expected: "1990-07-06" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
