import type { ChallengeDefinition } from "../../challenge-schema";

/** Drag & Drop (spec category #7). All variants share the `drag-drop` engine component. */
export const dragDropChallenges: ChallengeDefinition[] = [
  {
    id: "DRAGDROP-001",
    title: "HTML5 Drag/Drop — File onto Upload Zone",
    categoryId: "drag-drop",
    component: "drag-drop",
    variant: "html5-file-dropzone",
    behavior: ["drag-drop"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A native HTML5 draggable card (\"invoice.pdf\") must be dragged onto a designated drop zone using the HTML5 Drag and Drop API.",
      dataNeeded: "None.",
      action: "Drag the \"invoice.pdf\" card onto the \"Drop files here\" zone.",
      expectedResult: "The drop zone lists \"invoice.pdf\" as attached and highlights green momentarily.",
      validationPoints: ["Drop zone's attached-file list contains \"invoice.pdf\"", "Dropping outside the zone has no effect"],
      automationConcepts: ["HTML5 dragstart/dragover/drop event sequence", "DataTransfer object", "Drop-target validation"],
    },
    validation: [{ kind: "contains", field: "attachedFiles", expected: "invoice.pdf" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "DRAGDROP-002",
    title: "Sortable List — Reorder Sprint Backlog",
    categoryId: "drag-drop",
    component: "drag-drop",
    variant: "sortable-list",
    behavior: ["drag-drop", "sortable"],
    environment: ["none"],
    dataSource: "static/sprint-backlog",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 4-item sprint backlog list can be reordered by dragging items up/down (JS-based drag, not native HTML5).",
      dataNeeded: "None — items are seeded: Design, Build, Test, Ship (in that order).",
      action: "Drag \"Test\" to the top of the list.",
      expectedResult: "New order is: Test, Design, Build, Ship.",
      validationPoints: ["First item in the list equals \"Test\"", "Relative order of the remaining 3 items is otherwise preserved"],
      automationConcepts: ["Mouse-based drag simulation (down, move, up)", "Array-order assertion", "Non-HTML5 custom drag implementations"],
    },
    validation: [{ kind: "equals", field: "backlogOrder.0", expected: "Test" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "DRAGDROP-003",
    title: "Exact Drop-Zone Validation — Container Assignment",
    categoryId: "drag-drop",
    component: "drag-drop",
    variant: "exact-dropzone-validation",
    behavior: ["drag-drop"],
    environment: ["none"],
    dataSource: "static/containers",
    difficulty: "expert",
    frameworks: ["playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Three shipping containers (A, B, C) each accept only crates matching their labeled temperature zone (Frozen/Chilled/Ambient). Dropping on the wrong zone snaps the crate back.",
      dataNeeded: "None.",
      action: "Drag the \"Frozen Salmon\" crate onto Container A (Frozen). Then try dragging it onto Container C (Ambient).",
      expectedResult: "Drop on Container A succeeds and the crate is assigned; drop on Container C is rejected and the crate returns to its origin.",
      validationPoints: ["Crate assignment equals \"Container A\" after the valid drop", "An invalid drop must not change the assignment"],
      automationConcepts: ["Precise drop-target geometry", "Negative-case drag/drop testing", "Snap-back animation synchronization"],
    },
    validation: [{ kind: "equals", field: "crateAssignment", expected: "Container A" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
];
