import type { ChallengeDefinition } from "../../challenge-schema";

/**
 * Dropdowns & Selection Controls (spec category #3) — the flagship category
 * demonstrating Component + Behavior + Data composition. All variants share
 * the ONE `dropdown` engine component.
 */
export const dropdownsChallenges: ChallengeDefinition[] = [
  {
    id: "DROPDOWN-001",
    title: "Static Single-Select — Ticket Priority",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "static-single",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/ticket-priority",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A static single-select dropdown listing ticket priorities (Low, Medium, High, Critical).",
      dataNeeded: "One selection from a fixed list.",
      action: "Open the dropdown and select \"High\".",
      expectedResult: "The dropdown's displayed value is \"High\" and the priority badge updates to \"High\".",
      validationPoints: ["Selected value equals \"High\"", "Only one option can be selected at a time"],
      automationConcepts: ["Locator", "Select action", "Assertion on selected value"],
    },
    validation: [{ kind: "equals", field: "priority", expected: "High" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-002",
    title: "Static Multi-Select — Assign Reviewers",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "static-multi",
    behavior: ["static", "multi-select"],
    environment: ["none"],
    dataSource: "static/reviewers",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A real dropdown trigger that opens a checkbox list for assigning multiple code reviewers to a pull request.",
      dataNeeded: "Zero or more selections from a fixed list of 6 reviewers.",
      action: "Click the \"Select reviewers\" dropdown to open the panel, select \"Priya Sharma\" and \"Wei Chen\", then use \"Select All\", then \"Clear All\".",
      expectedResult: "Dropdown panel opens/closes on trigger click and outside click; chip list reflects current selections at every step; \"Select All\" selects all 6; \"Clear All\" empties the list.",
      validationPoints: ["Selected list contains exactly the chosen names", "Select All results in all options selected", "Clear All results in an empty selection"],
      automationConcepts: ["Multi-select interaction", "Open/close dropdown panel", "Select All / Clear All bulk actions", "Array-equality assertion"],
    },
    validation: [{ kind: "contains", field: "reviewers", expected: "Priya Sharma" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-003",
    title: "Searchable Dropdown — Product Catalog",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "searchable-single",
    behavior: ["static", "searchable"],
    environment: ["none"],
    dataSource: "static/products-500",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A type-ahead searchable dropdown filtering a 500-item product catalog client-side as you type.",
      dataNeeded: "Search text, e.g. \"Wireless\".",
      action: "Type \"Wireless\" into the search box and select \"Wireless Mechanical Keyboard\".",
      expectedResult: "Options filter to only matches containing \"Wireless\"; selecting one closes the list and shows the chosen product.",
      validationPoints: ["Filtered option count decreases as you type", "Selected product name equals the exact match"],
      automationConcepts: ["Type-ahead filtering", "Dynamic option-count assertion", "Select-after-filter pattern"],
      edgeCases: ["Search term matching zero products must show an explicit empty state, not a blank list"],
    },
    validation: [{ kind: "equals", field: "selectedProduct", expected: "Wireless Mechanical Keyboard" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-004",
    title: "API-Driven Dropdown — Department List",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "api-departments",
    behavior: ["api", "delayed"],
    environment: ["none"],
    dataSource: "api/departments",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Options are fetched from `GET /api/lab/departments` on dropdown open, with a realistic ~800ms network delay.",
      dataNeeded: "None — the tester only opens the dropdown and selects a department.",
      action: "Click the dropdown and select \"Engineering\" once options finish loading.",
      expectedResult: "A loading spinner shows for ~800ms, then real options render; selecting one updates the field.",
      validationPoints: ["Dropdown shows a loading state before options exist", "Options exactly match the API response", "Selected value equals \"Engineering\""],
      automationConcepts: ["API synchronization", "Network wait / auto-wait", "Loading → loaded state assertion"],
      edgeCases: ["Use `?mode=random` on the same endpoint to occasionally simulate a failed load (see error state)."],
    },
    validation: [{ kind: "equals", field: "department", expected: "Engineering" }],
    mode: { deterministic: true, randomAvailable: true },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-005",
    title: "Dependent Dropdown — Country → State → City",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "dependent-geo",
    behavior: ["api", "dependent", "cascading", "delayed"],
    environment: ["none"],
    dataSource: "api/geo",
    difficulty: "expert",
    frameworks: ["selenium", "playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Loads State options after a Country is selected, and City options after a State is selected. Each level calls a real backend endpoint.",
      dataNeeded: "Country selection, then State selection.",
      action: "Select \"India\", then select \"Karnataka\".",
      expectedResult: "The City dropdown is populated with cities belonging to Karnataka (e.g. Bengaluru, Mysuru, Mangaluru).",
      validationPoints: ["State dropdown is disabled until a Country is chosen", "City dropdown is disabled until a State is chosen", "City options belong exclusively to the selected State"],
      automationConcepts: ["Locator → select → wait → API synchronization → assertion", "Cascading dependency chains", "Disabled-until-ready pattern"],
      edgeCases: ["Changing Country after a State/City are chosen must reset both downstream fields"],
      hints: ["Watch network calls to /api/geo/states?country=IN and /api/geo/cities?state=KA"],
    },
    validation: [
      { kind: "equals", field: "country", expected: "India" },
      { kind: "equals", field: "state", expected: "Karnataka" },
      { kind: "contains", field: "availableCities", expected: "Bengaluru" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 6,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-006",
    title: "Grouped Dropdown with Disabled Options — Shipping Method",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "grouped-disabled",
    behavior: ["static", "grouped"],
    environment: ["none"],
    dataSource: "static/shipping-methods",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Shipping methods grouped under \"Domestic\" and \"International\" optgroups; some options (e.g. \"Same-Day\") are disabled for the current order.",
      dataNeeded: "One enabled selection.",
      action: "Attempt to select the disabled \"Same-Day (Domestic)\" option, then select the enabled \"Standard (International)\" option.",
      expectedResult: "The disabled option cannot be selected; the enabled option can be selected and reflects in the summary.",
      validationPoints: ["Disabled option remains unselected after attempted click", "Enabled option becomes the selected value"],
      automationConcepts: ["Grouped option (optgroup) locating", "Disabled-option negative assertion"],
    },
    validation: [{ kind: "equals", field: "shippingMethod", expected: "Standard (International)" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-007",
    title: "Radio Toggle Enables/Disables a Dependent Dropdown",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "radio-enables-dropdown",
    behavior: ["dependent"],
    environment: ["none"],
    dataSource: "static/approval-workflow",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Requires manager approval?\" Yes/No radio controls whether the \"Approver\" dropdown below it is enabled at all \u2014 a very common conditional-form pattern (approval workflows, optional fields, etc.).",
      dataNeeded: "Radio choice \"Yes\", then one approver selection.",
      action: "Confirm the Approver dropdown is disabled by default (\"No\" is selected), switch the radio to \"Yes\", then select \"Priya Sharma\" as approver.",
      expectedResult: "Approver dropdown is disabled while \"No\" is selected and becomes enabled immediately when \"Yes\" is chosen; switching back to \"No\" disables it again and clears the selection.",
      validationPoints: ["Dropdown has the disabled attribute while radio=\"No\"", "Dropdown becomes enabled the instant radio=\"Yes\" is selected", "Selecting \"No\" again clears any previously chosen approver"],
      automationConcepts: ["Conditional enablement driven by a sibling control", "Disabled-attribute polling after state change", "Clearing dependent state on toggle-back"],
    },
    validation: [{ kind: "equals", field: "approver", expected: "Priya Sharma" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-008",
    title: "Parent Dropdown Changes Child Dropdown's Entire Option Set",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "parent-changes-child-options",
    behavior: ["dependent", "cascading"],
    environment: ["none"],
    dataSource: "static/leave-reasons",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Selecting a \"Leave Type\" (Sick / Vacation / Personal) completely replaces the options in the \"Reason\" dropdown with a list specific to that leave type (not just a filtered subset).",
      dataNeeded: "Leave type \"Vacation\", then a matching reason.",
      action: "Select \"Vacation\", observe the Reason options change, then select \"Family Trip\".",
      expectedResult: "Reason options for \"Vacation\" are entirely different from those for \"Sick\" or \"Personal\"; switching Leave Type resets any previously chosen Reason.",
      validationPoints: ["Reason options exactly match the seeded list for the selected Leave Type", "Previously selected Reason is cleared after changing Leave Type", "Final selected reason equals \"Family Trip\""],
      automationConcepts: ["Full option-set replacement (not just filtering)", "Verifying stale selections are cleared on parent change"],
    },
    validation: [
      { kind: "equals", field: "leaveType", expected: "Vacation" },
      { kind: "equals", field: "leaveReason", expected: "Family Trip" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-009",
    title: "Type-to-Create — Dropdown Populated from a Text Field",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "type-to-create-from-textfield",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Typing a tag name into a text field and clicking \"Add\" appends it as a new option in the \"Tags\" dropdown below \u2014 the dropdown's contents are entirely user-generated, not pre-seeded.",
      dataNeeded: "String tag names, e.g. \"regression\", \"smoke\".",
      action: "Type \"regression\" and click Add, type \"smoke\" and click Add, then open the Tags dropdown and select \"regression\".",
      expectedResult: "Both typed tags appear as selectable dropdown options in the order they were added, and selecting one updates the current tag.",
      validationPoints: ["Dropdown option list contains exactly the tags typed, in order", "Selecting an option sets it as the current tag", "Adding an empty or duplicate tag is rejected"],
      automationConcepts: ["Dynamically generated option lists driven by user input", "Verifying dropdown contents reflect prior actions elsewhere on the page", "Duplicate/empty-input guard testing"],
    },
    validation: [
      { kind: "contains", field: "createdTags", expected: "regression" },
      { kind: "equals", field: "selectedTag", expected: "regression" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "DROPDOWN-010",
    title: "Click-to-Load Dropdown — 2.5s Load Delay on Open",
    categoryId: "dropdowns",
    component: "dropdown",
    variant: "click-to-load-delayed",
    behavior: ["api", "delayed", "lazy-loaded"],
    environment: ["none"],
    dataSource: "api/lab-assignees",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "The \"Assigned Engineer\" dropdown fetches its option list only when the tester clicks to open it, and the (deterministic) network call takes ~2.5 seconds before options appear.",
      dataNeeded: "None.",
      action: "Click the dropdown to open it, wait for the options to finish loading (do not assume they're instant), then select \"Wei Chen\".",
      expectedResult: "A loading indicator is visible for ~2.5s immediately after opening; the real option list only renders once loading completes.",
      validationPoints: ["Loading state is shown before options exist", "Attempting to select before load-complete has no matching option to click", "Selected engineer equals \"Wei Chen\" after the load finishes"],
      automationConcepts: ["Auto-wait for asynchronously-loaded dropdown options", "Avoiding flaky tests that assume dropdowns open instantly", "Explicit wait-for-element-count patterns"],
    },
    validation: [{ kind: "equals", field: "assignedEngineer", expected: "Wei Chen" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
