import type { ChallengeDefinition } from "../../challenge-schema";

/** Dynamic Elements (spec category #22). All variants share the `dynamic-dom` engine component. */
export const dynamicElementsChallenges: ChallengeDefinition[] = [
  {
    id: "DYNAMIC-001",
    title: "Regenerated ID/Class with a Stable data-testid",
    categoryId: "dynamic-elements",
    component: "dynamic-dom",
    variant: "regenerated-id-stable-testid",
    behavior: ["dynamic-id"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Session Panel\" (Session note text field, Session scope radio group, Session region dropdown) plus a \"Refresh session token\" button all regenerate their `id` and `class` attributes on every interaction (e.g. `note_48392` \u2192 `note_92831`), but every control keeps a stable `data-testid`. Unlike DYNAMIC-002, the DOM nodes stay connected the whole time \u2014 only the id/class attribute VALUES change. The page includes an in-app \"Learn\" panel plus a hands-on test that captures a real id, proves a locator built on it breaks, and proves the stable data-testid keeps working.",
      dataNeeded: "A session note string, a session scope selection, a session region selection.",
      action: "Fill the Session note, pick a Session scope, and choose a Session region (all located via their stable data-testid). Separately, capture the Session note field's current id, interact with any field to force a regeneration, then look up the old id (should fail) and the stable testid (should still work). Also click \"Refresh session token\" 3 times.",
      expectedResult: "Each field's value is captured correctly via its stable data-testid regardless of how many times id/class regenerate. The old captured id lookup returns null after regeneration; the data-testid lookup keeps succeeding. Click count reaches 3 even though the button's id/class changed after every click.",
      validationPoints: [
        "Session note equals \"Approved\"",
        "Session scope equals \"readwrite\"",
        "Session region equals \"EU\"",
        "The id-locator check reports \"confirmed broken\" (old id no longer resolves)",
        "The stable-testid check reports \"confirmed works\"",
        "clickCount equals 3",
      ],
      automationConcepts: ["Preferring stable data-testid/data-qa attributes over volatile id/class", "Avoiding brittle locators tied to generated attributes", "Attribute churn vs node identity (contrast with stale element references)"],
      edgeCases: ["A locator built from the id captured before an interaction will fail on the very next interaction \u2014 this is the point of the exercise."],
    },
    validation: [
      { kind: "equals", field: "sessionNote", expected: "Approved" },
      { kind: "equals", field: "sessionScope", expected: "readwrite" },
      { kind: "equals", field: "sessionRegion", expected: "EU" },
      { kind: "truthy", field: "idLocatorBrokenConfirmed" },
      { kind: "truthy", field: "stableTestIdConfirmed" },
      { kind: "equals", field: "clickCount", expected: 3 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DYNAMIC-002",
    title: "Element Recreated on Interval (Identity Changes, Content Stable)",
    categoryId: "dynamic-elements",
    component: "dynamic-dom",
    variant: "element-recreated-on-interval",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Live Ticket Form\" (Comment text field, Priority radio group, Assignee dropdown) is destroyed and re-created as brand-new DOM nodes every 2 seconds (not just re-rendered), which invalidates any previously-held element handle/reference — including handles to form controls, not just text labels. The page includes an in-app \"Learn\" panel plus a hands-on test that captures a real reference to the \"Medium\" priority radio button and proves it goes stale.",
      dataNeeded: "A comment string, a priority selection, and an assignee selection.",
      action: "Fill the Comment field, select a Priority, and choose an Assignee (re-querying fresh each time if the form regenerates mid-attempt — that's the point). Separately, capture a reference to the \"Medium\" priority radio, wait past a recreation cycle (2s+), then click the old reference and confirm it reports stale.",
      expectedResult: "Each form control's last successfully-submitted value is retained for grading even though the visible controls keep resetting to blank every cycle. The captured radio reference reports as no longer attached to the document (isConnected === false) once a recreation cycle has passed.",
      validationPoints: [
        "Comment field value equals \"Approved\"",
        "Priority equals \"medium\"",
        "Assignee equals \"Priya Nair\"",
        "The stale-reference check reports \"stale confirmed\" (captured radio detached from the document)",
      ],
      automationConcepts: [
        "Stale element reference handling on form controls (not just text)",
        "Re-querying vs caching element handles before every interaction",
        "DOM node identity vs rendered content",
        "node.isConnected / detached-node detection",
      ],
    },
    validation: [
      { kind: "equals", field: "liveComment", expected: "Approved" },
      { kind: "equals", field: "priority", expected: "medium" },
      { kind: "equals", field: "assignee", expected: "Priya Nair" },
      { kind: "truthy", field: "staleReferenceConfirmed" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
