import type { ChallengeDefinition } from "../../challenge-schema";

/** Dynamic XPath Challenges (spec category #23). All variants share the `dynamic-dom` engine component. */
export const dynamicXPathChallenges: ChallengeDefinition[] = [
  {
    id: "XPATH-001",
    title: "Locate by Partial Text Among Similar Siblings",
    categoryId: "dynamic-xpath",
    component: "dynamic-dom",
    variant: "xpath-contains-text-among-siblings",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "5 nearly-identical \"Ticket #TCK-100xx\" rows share the same class names; only the ticket number differs.",
      dataNeeded: "None.",
      action: "Locate the row containing \"TCK-10003\" (using contains()/partial text matching) and click its \"Resolve\" button.",
      expectedResult: "Only the TCK-10003 row's status changes to \"Resolved\"; all others remain \"Open\".",
      validationPoints: ["resolvedTicket equals \"TCK-10003\"", "The other 4 rows remain unaffected"],
      automationConcepts: ["XPath contains()/starts-with() for partial text", "Scoping a sibling action from a matched ancestor row"],
    },
    validation: [{ kind: "equals", field: "resolvedTicket", expected: "TCK-10003" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "XPATH-002",
    title: "Table-Row Relative XPath — Sibling Cell Lookup",
    categoryId: "dynamic-xpath",
    component: "dynamic-dom",
    variant: "table-row-relative-xpath",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A table of invoices has no unique row ids; you must find the row where the \"Vendor\" cell equals \"Globex Corp\" and then read its sibling \"Amount\" cell.",
      dataNeeded: "None.",
      action: "Find the row for vendor \"Globex Corp\" and read its Amount value.",
      expectedResult: "The correct amount ($4,820.00) is read from the sibling cell of the matched row, not a hardcoded row index.",
      validationPoints: ["readAmount equals \"$4,820.00\"", "Solution must not rely on a fixed row index since row order can change on reset"],
      automationConcepts: ["Parent/ancestor then descendant/sibling XPath traversal", "following-sibling:: axis usage", "Avoiding brittle nth-child row indexing"],
    },
    validation: [{ kind: "equals", field: "readAmount", expected: "$4,820.00" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
