import type { ChallengeDefinition } from "../../challenge-schema";

/** Error Handling (spec category #44) — realistic enterprise error pages. */
export const errorHandlingChallenges: ChallengeDefinition[] = [
  {
    id: "ERROR-404",
    title: "404 — Resource Not Found",
    categoryId: "error-handling",
    component: "error-page",
    variant: "http-404",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-failure",
    difficulty: "beginner",
    frameworks: ["generic-api", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Navigating to an unknown invoice ID renders a full enterprise 404 page with Retry/Back/Home/Support actions.",
      dataNeeded: "None — any non-existent invoice id triggers it.",
      action: "Open invoice \"INV-999999\" (does not exist).",
      expectedResult: "A 404 page renders with an Error ID, timestamp, and a \"Back to Invoices\" action.",
      validationPoints: ["HTTP status code returned is 404", "Page displays a unique Error ID and timestamp", "\"Back\" action returns to the invoice list"],
      automationConcepts: ["HTTP status assertion", "Error-page content assertion", "Recovery-action navigation"],
    },
    validation: [{ kind: "equals", field: "httpStatus", expected: 404 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "ERROR-500",
    title: "500 — Internal Server Error with Retry",
    categoryId: "error-handling",
    component: "error-page",
    variant: "http-500",
    behavior: ["api", "retry"],
    environment: ["none"],
    dataSource: "api/lab-failure",
    difficulty: "medium",
    frameworks: ["generic-api", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Calls `GET /api/lab/failure/500` which deterministically returns HTTP 500 on the first call and succeeds on Retry.",
      dataNeeded: "None.",
      action: "Trigger the report generation, observe the 500 error page, then click \"Retry\".",
      expectedResult: "First attempt shows a 500 error page with a Request ID; Retry succeeds and shows the report.",
      validationPoints: ["First response status is 500", "Retry response status is 200", "Request ID differs between attempts"],
      automationConcepts: ["Retry-logic testing", "Idempotent retry assertion", "Status-code transition (500 → 200)"],
    },
    validation: [{ kind: "equals", field: "httpStatus", expected: 200 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "ERROR-429",
    title: "429 — Rate Limited",
    categoryId: "error-handling",
    component: "error-page",
    variant: "http-429",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-failure",
    difficulty: "hard",
    frameworks: ["generic-api", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Calling `GET /api/lab/failure/429` more than 3 times within 10 seconds returns HTTP 429 with a `Retry-After` header.",
      dataNeeded: "None.",
      action: "Trigger the action 4 times quickly.",
      expectedResult: "The 4th call returns 429 and the UI shows \"Too many requests — retry in Ns\" using the server's Retry-After value.",
      validationPoints: ["4th response status is 429", "Displayed wait time matches the Retry-After header"],
      automationConcepts: ["Rate-limit simulation", "Response-header assertion", "Countdown UI synchronization"],
    },
    validation: [{ kind: "equals", field: "httpStatus", expected: 429 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
