import type { ChallengeDefinition } from "../../challenge-schema";

/** File Download (spec category #18). All variants share the `file-download` engine component. */
export const fileDownloadChallenges: ChallengeDefinition[] = [
  {
    id: "DOWNLOAD-001",
    title: "Dynamic Report Download with Timestamped Filename",
    categoryId: "file-download",
    component: "file-download",
    variant: "dynamic-filename-report",
    behavior: ["api", "delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Generate Report\" builds a report server-side (~600ms) and offers a download link whose filename includes the generation timestamp.",
      dataNeeded: "None.",
      action: "Click \"Generate Report\", wait for it to finish, then click the resulting download link.",
      expectedResult: "Filename matches the pattern `sales-report-YYYYMMDD-HHmm.csv` and the download completes.",
      validationPoints: ["Filename matches the timestamped pattern", "Link is absent until generation completes"],
      automationConcepts: ["Waiting for a download-ready state before asserting", "Regex-based dynamic filename assertion", "Playwright/Cypress download event handling"],
    },
    validation: [{ kind: "matches", field: "downloadedFileName", pattern: "^sales-report-\\d{8}-\\d{4}\\.csv$" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "DOWNLOAD-002",
    title: "CSV Export of Filtered Table",
    categoryId: "file-download",
    component: "file-download",
    variant: "csv-export",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Exports only the currently filtered/visible rows of a table to a downloadable CSV file (not the full unfiltered dataset).",
      dataNeeded: "None — filter is pre-applied to \"Engineering\" department.",
      action: "Click \"Export filtered rows to CSV\".",
      expectedResult: "The generated CSV content contains only Engineering rows, matching the visible table.",
      validationPoints: ["Exported row count equals the visible filtered row count (6)", "CSV filename ends with .csv"],
      automationConcepts: ["Reading Blob/download content for assertions", "Verifying exported data matches on-screen filtered state"],
    },
    validation: [{ kind: "equals", field: "exportedRowCount", expected: 6 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
