import type { ChallengeDefinition } from "../../challenge-schema";

/** File Upload (spec category #17). All variants share the `file-upload` engine component. */
export const fileUploadChallenges: ChallengeDefinition[] = [
  {
    id: "UPLOAD-001",
    title: "Single File Upload with Type/Size Validation",
    categoryId: "file-upload",
    component: "file-upload",
    variant: "single-with-validation",
    behavior: ["validated-on-submit"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Uploads an ID document; only .pdf/.jpg/.png are accepted and the max size is 2MB.",
      dataNeeded: "A file with an accepted extension and size under 2MB.",
      action: "Choose an oversized or wrong-extension file (rejected), then choose a valid one.",
      expectedResult: "Invalid files show \"Unsupported file type or size exceeds 2MB\"; a valid file shows the filename and a green check.",
      validationPoints: ["Rejected file leaves the upload slot empty", "Accepted file's name and size are displayed exactly as selected"],
      automationConcepts: ["setInputFiles / file-chooser automation", "Client-side extension and size validation testing"],
      edgeCases: ["A 0-byte file and an exactly-2MB file are boundary cases worth testing."],
    },
    validation: [{ kind: "matches", field: "uploadedFileName", pattern: "\\.(pdf|jpg|png)$" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "UPLOAD-002",
    title: "Drag-and-Drop Multi-File Upload with Progress",
    categoryId: "file-upload",
    component: "file-upload",
    variant: "multi-dragdrop-progress",
    behavior: ["drag-drop", "delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Drop up to 3 files onto the zone at once; each shows an independent progress bar that fills over ~1s before completing.",
      dataNeeded: "1-3 files.",
      action: "Drop 2 files onto the zone and wait for both progress bars to reach 100%.",
      expectedResult: "Both files appear immediately with a 0% bar, and each independently reaches \"Uploaded\" without blocking the other.",
      validationPoints: ["File count in the completed list equals 2", "Each file transitions uploading -> uploaded independently"],
      automationConcepts: ["DataTransfer with multiple files", "Polling multiple independent async completions"],
    },
    validation: [{ kind: "equals", field: "uploadedCount", expected: 2 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "UPLOAD-003",
    title: "Required Upload with Remove and Replace",
    categoryId: "file-upload",
    component: "file-upload",
    variant: "required-remove-replace",
    behavior: ["validated-on-submit"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A required résumé upload with Remove (clears it) and Replace (re-opens the file picker) actions; the form cannot submit without a file.",
      dataNeeded: "One file, then optionally a second to replace it.",
      action: "Upload a file, click Remove, confirm submit is blocked, then upload again and submit.",
      expectedResult: "Submit is disabled while no file is attached and enabled once one is present.",
      validationPoints: ["Submit is disabled immediately after Remove", "Submit succeeds once a file is re-attached"],
      automationConcepts: ["Required-field gating on non-text controls", "Remove/replace state machine testing"],
    },
    validation: [{ kind: "truthy", field: "resumeAttached" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
