import type { ChallengeDefinition } from "../../challenge-schema";

/** Iframe Laboratory (spec category #28). All variants share the `iframe-lab` engine component. */
export const iframeLabChallenges: ChallengeDefinition[] = [
  {
    id: "IFRAME-001",
    title: "Text Input Inside a Single Iframe",
    categoryId: "iframe-lab",
    component: "iframe-lab",
    variant: "input-in-iframe",
    behavior: ["static"],
    environment: ["iframe"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Shipping Notes\" text field is rendered inside an `<iframe>` document, not the main page.",
      dataNeeded: "String, e.g. \"Leave at front desk\".",
      action: "Switch into the iframe, type \"Leave at front desk\" into the notes field.",
      expectedResult: "The value entered inside the iframe is reported back to the parent page's summary panel.",
      validationPoints: ["Parent-page summary equals the exact text typed inside the iframe", "The field cannot be located without first switching into the iframe's context"],
      automationConcepts: ["Frame/iframe locator switching", "postMessage-based cross-frame communication", "Frame-scoped element queries"],
    },
    validation: [{ kind: "equals", field: "shippingNotes", expected: "Leave at front desk" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "IFRAME-002",
    title: "Nested Iframes — Main \u2192 Frame A \u2192 Frame B \u2192 Frame C",
    categoryId: "iframe-lab",
    component: "iframe-lab",
    variant: "triple-nested-iframe",
    behavior: ["static"],
    environment: ["nested-iframe"],
    dataSource: "static/none",
    difficulty: "expert",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Three iframes are nested inside one another (A contains B, B contains C); a button only exists inside the innermost frame C.",
      dataNeeded: "None.",
      action: "Drill down through Frame A \u2192 Frame B \u2192 Frame C and click \"Confirm\" inside Frame C.",
      expectedResult: "A confirmation message propagates back up to the main page.",
      validationPoints: ["Main-page confirmation flag is only set after the innermost frame's button is clicked", "The button is unreachable from the main document or Frame A/B directly"],
      automationConcepts: ["Multi-level frame traversal", "Frame-of-frame locator chaining (frameLocator().frameLocator())", "Message bubbling through multiple postMessage hops"],
    },
    validation: [{ kind: "equals", field: "nestedConfirmed", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
  {
    id: "IFRAME-003",
    title: "Dropdown Inside an Iframe",
    categoryId: "iframe-lab",
    component: "iframe-lab",
    variant: "dropdown-in-iframe",
    behavior: ["static"],
    environment: ["iframe"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Preferred Contact Method\" dropdown lives entirely inside an embedded iframe (e.g. a third-party widget pattern).",
      dataNeeded: "One selection: Email, Phone, or SMS.",
      action: "Switch into the iframe and select \"SMS\".",
      expectedResult: "The parent page's summary reflects \"SMS\" as the preferred contact method.",
      validationPoints: ["Selected value inside the iframe equals \"SMS\"", "Parent summary equals \"SMS\" after selection"],
      automationConcepts: ["Selecting options inside a frame-scoped context", "Cross-frame state synchronization"],
    },
    validation: [{ kind: "equals", field: "preferredContact", expected: "SMS" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
