import type { ChallengeDefinition } from "../../challenge-schema";

/** Images & Media (spec category #19). All variants share the `media` engine component. */
export const imagesMediaChallenges: ChallengeDefinition[] = [
  {
    id: "MEDIA-001",
    title: "Broken Image with Accessible Alt Fallback",
    categoryId: "images-media",
    component: "media",
    variant: "broken-image-alt-fallback",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A product image with an intentionally broken `src` still exposes a meaningful `alt` text, and the UI shows a visible fallback placeholder on error.",
      dataNeeded: "None.",
      action: "Observe the broken image tile; do not fix it, just verify its fallback behavior.",
      expectedResult: "A placeholder graphic and the text \"Image unavailable: Ergonomic Chair\" render in place of the broken image, and the `alt` attribute still equals \"Ergonomic Chair\".",
      validationPoints: ["img alt attribute equals \"Ergonomic Chair\" even though the image fails to load", "onError fallback UI is visible"],
      automationConcepts: ["Testing accessible-name presence independent of visual rendering", "img onError event handling", "Accessibility-first assertions"],
    },
    validation: [{ kind: "equals", field: "imageAlt", expected: "Ergonomic Chair" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "MEDIA-002",
    title: "Video Player — Play, Pause, Seek",
    categoryId: "images-media",
    component: "media",
    variant: "video-controls",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A training video player exposes Play/Pause and a seek bar reporting current playback time.",
      dataNeeded: "None.",
      action: "Click Play, let it run briefly, click Pause, then seek to 30 seconds.",
      expectedResult: "Play toggles to Pause; the reported time freezes on pause; seeking updates the current time to 30.",
      validationPoints: ["Playback state toggles between \"playing\" and \"paused\"", "currentTime equals 30 after seeking"],
      automationConcepts: ["HTMLMediaElement property assertions (currentTime, paused)", "Time-based state polling"],
    },
    validation: [{ kind: "equals", field: "currentTime", expected: 30 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
