import type { ChallengeDefinition } from "../../challenge-schema";

/** Input & Form Controls (spec category #2). All share the `text-input` engine component. */
export const inputControlsChallenges: ChallengeDefinition[] = [
  {
    id: "INPUT-001",
    title: "Required Employee Full Name",
    categoryId: "input-controls",
    component: "text-input",
    variant: "required-basic",
    behavior: ["validated-on-submit"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A required text field for an employee's full name, validated on form submit.",
      dataNeeded: "String, e.g. \"Ananya Rao\".",
      action: "Leave the field empty and submit, then fill \"Ananya Rao\" and submit again.",
      expectedResult: "Empty submit shows \"Full name is required\"; valid submit shows a success banner.",
      validationPoints: ["Error message text on empty submit", "Success state after valid submit", "Field value persists exactly as typed"],
      automationConcepts: ["Locator", "Type", "Clear", "Submit", "Read value", "Error-message assertion"],
      edgeCases: ["Leading/trailing whitespace-only input should still be treated as empty"],
    },
    validation: [{ kind: "equals", field: "fullName", expected: "Ananya Rao" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-002",
    title: "Corporate Email — Validate on Blur",
    categoryId: "input-controls",
    component: "text-input",
    variant: "email-blur-validation",
    behavior: ["validated-on-blur"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Corporate email field that validates format only after the field loses focus (blur), not while typing.",
      dataNeeded: "Email string, e.g. \"ananya.rao@globalcorp.com\".",
      action: "Type \"invalid-email\" then Tab away (blur); then correct it to a valid email and blur again.",
      expectedResult: "Invalid format shows \"Enter a valid corporate email\" only after blur; valid email clears the error.",
      validationPoints: ["No error while typing (before blur)", "Error appears exactly on blur with invalid value", "Error clears once value becomes valid"],
      automationConcepts: ["Blur event triggering", "Regex-based validation", "Timing of validation vs typing"],
    },
    validation: [{ kind: "matches", field: "email", pattern: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-003",
    title: "Password — Minimum Strength",
    categoryId: "input-controls",
    component: "text-input",
    variant: "password-strength",
    behavior: ["validated-live"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Password field with a live strength meter requiring 8+ chars, one number, one uppercase letter.",
      dataNeeded: "String, e.g. \"Global2026Pass\".",
      action: "Type a weak password (e.g. \"abc\"), observe strength; then type \"Global2026Pass\".",
      expectedResult: "Strength meter reads \"Weak\" for short input and \"Strong\" once all rules are satisfied.",
      validationPoints: ["Strength label updates on every keystroke", "\"Strong\" only when length>=8, has digit, has uppercase"],
      automationConcepts: ["Live/debounced validation", "Multi-rule assertion", "Reading computed label text"],
    },
    validation: [
      { kind: "range", field: "password.length", min: 8 },
      { kind: "matches", field: "password", pattern: "[A-Z]" },
      { kind: "matches", field: "password", pattern: "[0-9]" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-004",
    title: "Purchase Order Quantity — Numeric Range",
    categoryId: "input-controls",
    component: "text-input",
    variant: "number-range",
    behavior: ["validated-on-blur"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Numeric-only quantity field for a purchase order, must be between 1 and 500.",
      dataNeeded: "Integer, e.g. 25.",
      action: "Enter 0, blur (expect error); enter 25, blur (expect success).",
      expectedResult: "Out-of-range values show \"Quantity must be between 1 and 500\"; in-range values are accepted.",
      validationPoints: ["Non-numeric characters are rejected while typing", "Range validation runs on blur"],
      automationConcepts: ["Numeric input constraint", "Range assertion", "Boundary-value testing (0, 1, 500, 501)"],
      edgeCases: ["Boundary values 1 and 500 must be valid; 0 and 501 must be invalid"],
    },
    validation: [{ kind: "range", field: "quantity", min: 1, max: 500 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-005",
    title: "Support Ticket Description — Character Counter",
    categoryId: "input-controls",
    component: "text-input",
    variant: "textarea-counter",
    behavior: ["validated-live"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Multiline textarea (max 500 chars) with a live \"n / 500\" character counter.",
      dataNeeded: "Free text, e.g. a support ticket description.",
      action: "Type a description and watch the counter; try to exceed 500 characters.",
      expectedResult: "Counter updates on every keystroke; input is hard-capped at 500 characters.",
      validationPoints: ["Counter equals current character length", "Textarea value never exceeds 500 characters"],
      automationConcepts: ["Live counter assertion", "Max-length boundary testing"],
    },
    validation: [{ kind: "range", field: "description.length", min: 0, max: 500 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-006",
    title: "Username Availability — Debounced API Check",
    categoryId: "input-controls",
    component: "text-input",
    variant: "debounced-username-check",
    behavior: ["api", "debounced", "validated-live"],
    environment: ["none"],
    dataSource: "api/username-availability",
    difficulty: "hard",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Checks username availability against a backend endpoint 500ms after typing stops (debounced), showing a loading, then available/taken state.",
      dataNeeded: "String username. \"admin\" and \"qa_lead\" are seeded as already taken.",
      action: "Type \"admin\" (expect Taken); clear and type \"new_engineer_42\" (expect Available).",
      expectedResult: "A loading indicator appears during the debounce+API window, then resolves to \"Available\" or \"Taken\".",
      validationPoints: ["No API call fires until 500ms after the last keystroke", "Correct final state per seeded username list"],
      automationConcepts: ["Debounce timing", "Network wait / API synchronization", "Loading-then-resolved state assertion"],
      edgeCases: ["Rapid retyping before debounce fires must not trigger duplicate requests"],
    },
    validation: [{ kind: "equals", field: "availability", expected: "available" }],
    mode: { deterministic: true, randomAvailable: true },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-007",
    title: "Read-Only Employee ID / Disabled Legacy Field / Pre-filled Department",
    categoryId: "input-controls",
    component: "text-input",
    variant: "readonly-prefilled",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/employee-profile",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Three fields side by side: a read-only Employee ID, a disabled legacy \"Fax Number\" field, and a pre-filled Department field.",
      dataNeeded: "None — values are seeded.",
      action: "Attempt to edit each of the three fields.",
      expectedResult: "Employee ID rejects typing but is copyable; Fax Number is fully disabled (not focusable); Department is pre-filled with \"Engineering\" and editable.",
      validationPoints: ["Employee ID has `readonly` attribute", "Fax Number has `disabled` attribute", "Department initial value equals \"Engineering\""],
      automationConcepts: ["Readonly vs disabled distinction", "Attribute assertions", "Initial-value assertion"],
    },
    validation: [{ kind: "equals", field: "department", expected: "Engineering" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-008",
    title: "Radio Selection Reveals Additional Input Fields",
    categoryId: "input-controls",
    component: "text-input",
    variant: "radio-reveals-fields",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Two independent radio-reveal scenarios on one page. (1) \"Do you have a referral code?\" Yes/No radio; selecting \"Yes\" reveals a \"Referral Code\" text field that does not exist in the DOM at all while \"No\" is selected. (2) \"Are you a resident of India?\" Yes/No radio; selecting \"Yes\" reveals a State dropdown and a Gender radio group, plus a \"Need visa to work in India?\" Yes/No radio group that is auto-set to \"No\" and disabled/locked so it can never be changed.",
      dataNeeded: "Referral code string, e.g. \"FRIEND2026\"; an Indian state selection; a gender selection.",
      action: "Confirm the referral field is absent by default, select \"Yes\", then type \"FRIEND2026\" into the revealed field. Separately, select \"Yes\" for \"Are you a resident of India?\", pick a state and a gender, then verify the \"Need visa to work in India?\" radio is locked on \"No\" and clicking \"Yes\" has no effect.",
      expectedResult: "The referral field only appears after selecting \"Yes\"; switching back to \"No\" removes it (and its value) again. The State dropdown, Gender radios, and visa radio group only render once \"resident of India\" is \"Yes\"; the visa radio group always shows \"No\" checked and both options disabled, so it cannot be switched to \"Yes\" by any interaction.",
      validationPoints: [
        "Referral field is not present in the DOM while \"No\" is selected",
        "Referral field appears and accepts input once \"Yes\" is selected",
        "Switching back to \"No\" discards the entered referral value",
        "State and Gender fields only appear once \"resident of India\" is \"Yes\"",
        "\"Need visa to work in India?\" is locked to \"No\" and both radio options are disabled",
      ],
      automationConcepts: [
        "Conditionally-rendered (not just hidden) field testing",
        "Presence/absence assertions vs visibility assertions",
        "State-loss-on-toggle verification",
        "Asserting a control's checked value AND its disabled state together",
      ],
    },
    validation: [
      { kind: "equals", field: "referralCode", expected: "FRIEND2026" },
      { kind: "truthy", field: "indiaState" },
      { kind: "truthy", field: "gender" },
      { kind: "equals", field: "visaRequired", expected: "no" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "INPUT-009",
    title: "Min/Max Character Length Field (1\u2013200)",
    categoryId: "input-controls",
    component: "text-input",
    variant: "min-max-char-length",
    behavior: ["validated-on-blur", "validated-live"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Product SKU Description\" field enforces both a minimum (1 char \u2014 cannot be empty) and a maximum (200 chars \u2014 hard-capped) length, with a live counter showing \"n / 200\".",
      dataNeeded: "String between 1 and 200 characters.",
      action: "Try submitting empty (expect error), try typing more than 200 characters (input is capped), then enter a valid 10-character value and submit.",
      expectedResult: "Empty submission is rejected with \"This field is required\"; typing is hard-capped at exactly 200 characters; valid-length input submits successfully.",
      validationPoints: ["Empty value blocks submit with a visible error", "Field value length never exceeds 200 even when more is typed/pasted", "A 1\u2013200 character value submits successfully"],
      automationConcepts: ["Boundary-value testing (0, 1, 200, 201 characters)", "Paste-vs-type max-length enforcement", "Required + max-length combined validation"],
      edgeCases: ["Pasting a 500-character string at once must still truncate to 200, not just block further typing."],
    },
    validation: [
      { kind: "range", field: "skuDescription.length", min: 1, max: 200 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
