import type { ChallengeDefinition } from "../../challenge-schema";

/** Links & Navigation (spec category #5). All variants share the `link` engine component. */
export const linksNavigationChallenges: ChallengeDefinition[] = [
  {
    id: "LINK-001",
    title: "Same-Tab vs New-Tab Invoice Link",
    categoryId: "links-navigation",
    component: "link",
    variant: "same-vs-new-tab",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "beginner",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Two links open the same invoice: one navigates in the same tab, the other opens a new tab via `target=\"_blank\"`.",
      dataNeeded: "None.",
      action: "Click \"View Invoice (same tab)\", go back, then click \"View Invoice (new tab)\".",
      expectedResult: "First link replaces the current page; second link opens a new browser tab while the original page remains.",
      validationPoints: ["Same-tab link has no target attribute", "New-tab link has target=\"_blank\" and rel=\"noopener\"", "Original tab count increases only for the new-tab link"],
      automationConcepts: ["Window/tab handle switching", "target attribute assertion", "rel=noopener security check"],
    },
    validation: [{ kind: "equals", field: "newTabOpened", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "LINK-002",
    title: "JavaScript-Triggered Navigation",
    categoryId: "links-navigation",
    component: "link",
    variant: "js-triggered-navigation",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A styled `<span>` (not a real anchor) navigates via a JS click handler rather than an `href` — a common anti-pattern to detect.",
      dataNeeded: "None.",
      action: "Click \"Go to Reports\".",
      expectedResult: "The route changes to the Reports view even though the element is not a real link.",
      validationPoints: ["Element has no href attribute", "Clicking still triggers a route/state change", "Element is keyboard-activatable (Enter key) for accessibility"],
      automationConcepts: ["Locating non-anchor clickable elements", "Verifying navigation side-effects instead of href", "Keyboard-accessibility assertion"],
      edgeCases: ["Pressing Enter while focused must also navigate, since it isn't a native <a>"],
    },
    validation: [{ kind: "equals", field: "route", expected: "reports" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "LINK-003",
    title: "Query-Parameter and Hash-Fragment Links",
    categoryId: "links-navigation",
    component: "link",
    variant: "query-and-hash-links",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Two links: one appends a query string (`?tab=archived`), one jumps to an in-page anchor (`#section-notes`).",
      dataNeeded: "None.",
      action: "Click \"Archived Orders\" then click \"Jump to Notes\".",
      expectedResult: "URL updates with `?tab=archived`; the second click scrolls to and updates the URL with `#section-notes`.",
      validationPoints: ["Query string equals \"tab=archived\" after first click", "Hash equals \"section-notes\" after second click"],
      automationConcepts: ["URL query-string assertion", "URL hash assertion", "Scroll-into-view verification"],
    },
    validation: [
      { kind: "equals", field: "queryTab", expected: "archived" },
      { kind: "equals", field: "hash", expected: "section-notes" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
