import type { ChallengeDefinition } from "../../challenge-schema";

/** Lists & Cards (spec category #9). All variants share the `card` engine component. */
export const listsCardsChallenges: ChallengeDefinition[] = [
  {
    id: "CARD-001",
    title: "Favorite and Filter Product Cards",
    categoryId: "lists-cards",
    component: "card",
    variant: "favorite-filter",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/products-12",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A grid of 12 product cards, each with an image, price, and a favorite (heart) toggle.",
      dataNeeded: "None.",
      action: "Favorite \"Wireless Keyboard\" and \"USB-C Hub\", then toggle the \"Show favorites only\" switch.",
      expectedResult: "Only the 2 favorited cards remain visible when the filter is on.",
      validationPoints: ["Favorited card count equals 2", "Visible card count equals 2 when filter is active"],
      automationConcepts: ["Toggle-button state assertion", "Client-side filter verification", "Card grid locator strategy"],
    },
    validation: [{ kind: "equals", field: "favoriteCount", expected: 2 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "CARD-002",
    title: "Card Menu Actions — Edit / Duplicate / Delete",
    categoryId: "lists-cards",
    component: "card",
    variant: "card-menu-actions",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/projects-4",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Each project card has a three-dot menu with Edit, Duplicate, and Delete actions.",
      dataNeeded: "None.",
      action: "Open the menu on \"Atlas Migration\" and choose \"Duplicate\".",
      expectedResult: "A new card \"Atlas Migration (Copy)\" appears in the grid.",
      validationPoints: ["Card count increases by exactly 1", "New card title equals \"Atlas Migration (Copy)\""],
      automationConcepts: ["Overflow/kebab menu interaction", "Dynamically appended DOM node assertion"],
    },
    validation: [{ kind: "contains", field: "projectTitles", expected: "Atlas Migration (Copy)" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "CARD-003",
    title: "Lazy-Loaded Card Feed (Infinite Scroll)",
    categoryId: "lists-cards",
    component: "card",
    variant: "lazy-loaded-feed",
    behavior: ["lazy-loaded", "infinite-scroll"],
    environment: ["none"],
    dataSource: "static/activity-feed",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An activity feed renders 10 cards at a time and loads 10 more when the user scrolls near the bottom, up to 50 total.",
      dataNeeded: "None.",
      action: "Scroll to the bottom of the feed repeatedly until no more cards load.",
      expectedResult: "Card count grows in increments of 10 up to exactly 50, then an \"You're all caught up\" end-of-list message appears.",
      validationPoints: ["Final card count equals 50", "End-of-list message appears only after the 50th card loads", "No duplicate card ids appear"],
      automationConcepts: ["Scroll-triggered lazy loading", "Polling/wait-until-count-stabilizes pattern", "Duplicate-detection assertion"],
    },
    validation: [{ kind: "equals", field: "cardCount", expected: 50 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
];
