import type { ChallengeDefinition } from "../../challenge-schema";

/** Menus & Navigation (spec category #10). All variants share the `menu` engine component. */
export const menusNavigationChallenges: ChallengeDefinition[] = [
  {
    id: "MENU-001",
    title: "Multi-Level Dropdown Navigation Menu — E-Commerce Header",
    categoryId: "menus-navigation",
    component: "menu",
    variant: "multi-level-dropdown-nav",
    behavior: ["static", "cascading"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A real e-commerce-style header with \"Products\", \"Company\", and \"Support\" top-level menus. \"Products\" contains a second-level flyout (\"Electronics\", \"Home & Kitchen\") that opens a further submenu on click. Selecting any leaf item closes every open menu and opens a real page below (breadcrumb + title + content), driven by an actual URL query parameter.",
      dataNeeded: "None.",
      action: "Click \"Products\", then click \"Electronics\" to open its flyout submenu, then click \"Laptops\".",
      expectedResult: "The page panel shows breadcrumb \"Home / Products / Electronics / Laptops\" and title \"Laptops\"; the browser URL gains `?page=%2Fproducts%2Felectronics%2Flaptops`; all menus close after the selection.",
      validationPoints: ["visitedPath equals \"/products/electronics/laptops\"", "Only one top-level menu (and one flyout) is open at a time", "Clicking outside the nav closes any open menu"],
      automationConcepts: ["Multi-level (nested) menu traversal", "Flyout/submenu locate-then-click sequencing", "URL query parameter as real, assertable navigation state", "Click-outside-to-close menu behavior"],
    },
    validation: [{ kind: "equals", field: "visitedPath", expected: "/products/electronics/laptops" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "MENU-002",
    title: "Mobile Hamburger Menu with Collapsible Sections",
    categoryId: "menus-navigation",
    component: "menu",
    variant: "mobile-hamburger-collapsible",
    behavior: ["static", "grouped"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A mobile-style hamburger button reveals a drawer containing collapsible sections (\"Company\", \"Support\"), each expandable independently like an accordion. Selecting a leaf item inside a section opens a real page below (breadcrumb + title + content), driven by an actual URL query parameter.",
      dataNeeded: "None.",
      action: "Click the hamburger button to open the drawer, expand \"Support\", then click \"Help Center\".",
      expectedResult: "The page panel shows breadcrumb \"Home / Support / Help Center\" and title \"Help Center\"; the drawer and section both close after the selection.",
      validationPoints: ["visitedPath equals \"/support/help-center\"", "The drawer is collapsed again after selecting a leaf item"],
      automationConcepts: ["Hamburger/drawer toggle pattern", "Accordion-style collapsible menu sections", "aria-expanded assertions on both the drawer and its sections"],
    },
    validation: [{ kind: "equals", field: "visitedPath", expected: "/support/help-center" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "MENU-003",
    title: "Side Navigation Menu with an Adjacent Submenu Panel",
    categoryId: "menus-navigation",
    component: "menu",
    variant: "side-nav-adjacent-submenu",
    behavior: ["static", "cascading", "grouped"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A vertical left-hand side menu (Products / Company / Support) where clicking an item opens a SECOND vertical panel directly beside it (not a dropdown below) showing that item's options. Inside the \"Products\" panel, \"Electronics\" and \"Home & Kitchen\" are further expandable groups. Unlike the dropdown/hamburger variants, this side menu stays open (persistent, like a real admin dashboard) and highlights the active trail after you pick a leaf item, which opens a real page (breadcrumb + title + content) driven by an actual URL query parameter.",
      dataNeeded: "None.",
      action: "Click \"Products\" in the side menu, expand \"Electronics\" in the adjacent panel, then click \"Laptops\".",
      expectedResult: "The page panel shows breadcrumb \"Home / Products / Electronics / Laptops\" and title \"Laptops\"; the side menu and its adjacent submenu panel both remain open and visible, with \"Products\" and \"Laptops\" marked as the active trail (aria-current).",
      validationPoints: ["visitedPath equals \"/products/electronics/laptops\"", "The submenu panel is positioned beside (not below) the side menu and stays open after selecting a leaf item", "The active side-menu item and active leaf are marked via aria-current"],
      automationConcepts: ["Two-pane persistent side navigation (menu + adjacent submenu panel)", "Distinguishing persistent nav state from closable dropdown/drawer nav state", "aria-current assertions for \"active trail\" highlighting"],
    },
    validation: [{ kind: "equals", field: "visitedPath", expected: "/products/electronics/laptops" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "MENU-004",
    title: "Enterprise Hover-to-Reveal Side Menu with Auto-Collapse",
    categoryId: "menus-navigation",
    component: "menu",
    variant: "enterprise-hover-collapse-sidenav",
    behavior: ["static", "grouped"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A real enterprise-website-style side menu (Products / Company / Support). Hovering the mouse over an item reveals its submenu beside it; moving the mouse away (without entering the submenu) hides it again — the submenu is NOT click-triggered. Clicking a leaf item in the submenu opens a real page (breadcrumb + title + content, via an actual URL query parameter) and automatically collapses the whole side menu down to a narrow icon rail.",
      dataNeeded: "None.",
      action: "Hover over \"Products\" (do not click it) until its submenu appears, then click \"Laptops\" inside the submenu.",
      expectedResult: "The submenu only appears while hovering \"Products\" (or the submenu itself) and disappears the instant the mouse leaves both; clicking \"Laptops\" opens the Laptops page and the side menu immediately collapses to a narrow rail.",
      validationPoints: ["The submenu is hidden until the corresponding item is hovered, and hides again on mouse-out without a click", "visitedPath equals \"/products/electronics/laptops\"", "The side menu reports collapsed specifically because a leaf item was selected (not because of the manual collapse toggle)"],
      automationConcepts: ["Hover-triggered visibility (mouseenter/mouseleave), not click-triggered", "\"Hover island\" pattern — trigger + submenu must both keep the menu open", "Real mouse hover() calls required in Selenium/Playwright (a plain .click() on a hidden item will fail)", "Post-navigation UI collapse as a side effect of a menu action"],
    },
    validation: [
      { kind: "equals", field: "visitedPath", expected: "/products/electronics/laptops" },
      { kind: "truthy", field: "sidebarCollapsedAfterSelect" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
