import type { ChallengeDefinition } from "../../challenge-schema";

/** Modals & Dialogs (spec category #13). All variants share the `modal` engine component. */
export const modalsDialogsChallenges: ChallengeDefinition[] = [
  {
    id: "MODAL-001",
    title: "Modal Closes on Outside Click and Escape",
    categoryId: "modals-dialogs",
    component: "modal",
    variant: "outside-click-and-escape",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An \"Edit Profile\" modal closes when clicking the dark overlay outside it, or pressing Escape.",
      dataNeeded: "None.",
      action: "Open the modal, click the overlay outside the dialog, reopen, then press Escape.",
      expectedResult: "Both interactions close the modal without saving any changes.",
      validationPoints: ["Modal is not present in the DOM (or aria-hidden) after each close method", "Focus returns to the triggering button after close"],
      automationConcepts: ["Overlay/backdrop click targeting", "Keyboard-driven dismissal (Escape)", "Focus-return accessibility check"],
    },
    validation: [{ kind: "equals", field: "modalOpen", expected: false }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "MODAL-002",
    title: "Non-Dismissible Modal — Terms Acceptance",
    categoryId: "modals-dialogs",
    component: "modal",
    variant: "non-dismissible",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A mandatory Terms of Service modal intentionally does NOT close on outside click or Escape — it can only be dismissed via its explicit \"Accept\" button.",
      dataNeeded: "None.",
      action: "Try clicking outside and pressing Escape (both should fail), then click \"Accept\".",
      expectedResult: "Modal remains open until \"Accept\" is explicitly clicked.",
      validationPoints: ["Modal remains present after outside click", "Modal remains present after Escape", "Modal closes only after clicking Accept"],
      automationConcepts: ["Negative-case dismissal testing", "Focus-trap verification (Tab cannot leave the modal)"],
    },
    validation: [{ kind: "equals", field: "termsAccepted", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "MODAL-003",
    title: "Nested Modal — Add Address from Checkout",
    categoryId: "modals-dialogs",
    component: "modal",
    variant: "nested-modal",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "From within a \"Checkout\" modal, clicking \"Add new address\" opens a second modal stacked on top of the first.",
      dataNeeded: "String street address.",
      action: "Open Checkout, click \"Add new address\", fill in \"221B Baker Street\", save, and confirm it returns you to Checkout with the address selected.",
      expectedResult: "The inner modal closes after save; the outer Checkout modal remains open with the new address pre-selected.",
      validationPoints: ["Exactly one modal is open after saving the address", "Selected address in Checkout equals \"221B Baker Street\""],
      automationConcepts: ["Modal-stack (z-index) scoping", "Locator scoping to the topmost dialog", "Cross-modal data hand-off"],
    },
    validation: [{ kind: "equals", field: "selectedAddress", expected: "221B Baker Street" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "MODAL-004",
    title: "Rich Form Popup \u2014 Closable Only via the X Button",
    categoryId: "modals-dialogs",
    component: "modal",
    variant: "form-modal-close-only",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Add Team Member\" opens a popup containing a Name field, a Role dropdown, a \"Send welcome email?\" radio, and a scrollable Terms box. Outside click and Escape are both intentionally disabled \u2014 the ONLY way to dismiss it is the explicit X button, and the background page must stay non-interactive while it's open.",
      dataNeeded: "String name, one role, one radio choice.",
      action: "Open the popup, try clicking outside and pressing Escape (both should fail to close it), fill in \"Diego Fernandez\" / \"Manager\" / \"Yes\", scroll the Terms box to the bottom, then click the X to close.",
      expectedResult: "Popup only closes via X; the underlying page's \"Team\" list becomes clickable again only after it closes, and shows the newly added member.",
      validationPoints: ["Popup remains open after outside click and after Escape", "Background \"Team\" list is not interactable while the popup is open", "New team member appears in the list only after closing via X"],
      automationConcepts: ["Distinguishing 'no dismiss handlers wired' from 'dismiss handler exists but is disabled'", "Background-interaction-blocked verification while a modal is open", "Locating and scrolling an element nested inside a modal"],
    },
    validation: [
      { kind: "contains", field: "teamMembers", expected: "Diego Fernandez" },
      { kind: "equals", field: "popupOpen", expected: false },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
];
