import type { ChallengeDefinition } from "../../challenge-schema";

/** Mouse Actions (spec category #6). Extends the `action-surface` engine component. */
export const mouseActionsChallenges: ChallengeDefinition[] = [
  {
    id: "MOUSE-001",
    title: "Coordinate Click on Canvas Heatmap",
    categoryId: "mouse-actions",
    component: "action-surface",
    variant: "coordinate-click",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "intentional-defect",
    guidance: {
      whatItDoes: "A 300x150 analytics heatmap surface (rendered as a plain div, no semantic markup) reports the exact x/y offset of a click.",
      dataNeeded: "Target coordinate, e.g. (120, 60).",
      action: "Click at approximately x=120, y=60 relative to the heatmap's top-left corner.",
      expectedResult: "The readout shows the clicked coordinate within a 5px tolerance.",
      validationPoints: ["Reported x is within [115,125]", "Reported y is within [55,65]"],
      automationConcepts: ["Offset/coordinate-based click()", "Element bounding-box math", "Tolerance-based numeric assertion"],
      edgeCases: ["This surface intentionally has no accessible name — it is a real-world canvas/heatmap pattern with a known accessibility defect."],
    },
    validation: [
      { kind: "range", field: "clickX", min: 115, max: 125 },
      { kind: "range", field: "clickY", min: 55, max: 65 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "MOUSE-002",
    title: "Click-and-Hold to Arm Emergency Stop",
    categoryId: "mouse-actions",
    component: "action-surface",
    variant: "click-and-hold",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A safety-critical \"Emergency Stop\" button requires a mouse-down held for 1.5s before it arms, preventing accidental single clicks.",
      dataNeeded: "None.",
      action: "Press and hold the mouse button on \"Hold to Stop\" for at least 1.5 seconds, then release.",
      expectedResult: "A progress ring fills over 1.5s; releasing early cancels, releasing after 1.5s arms the stop and shows \"STOPPED\".",
      validationPoints: ["Releasing before 1.5s leaves state \"idle\"", "Releasing at/after 1.5s sets state \"stopped\""],
      automationConcepts: ["mouse.down() / wait / mouse.up() sequencing", "Timing-sensitive interaction testing"],
    },
    validation: [{ kind: "equals", field: "stopState", expected: "stopped" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "MOUSE-003",
    title: "Mouse-Wheel Zoom on Product Image",
    categoryId: "mouse-actions",
    component: "action-surface",
    variant: "mouse-wheel-zoom",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Scrolling the mouse wheel over a product image zooms it in/out between 100% and 300%.",
      dataNeeded: "None.",
      action: "Scroll up (zoom in) over the image 3 times, then scroll down (zoom out) once.",
      expectedResult: "Zoom level increases by 25% per upward scroll step and decreases by 25% per downward step, clamped to [100, 300].",
      validationPoints: ["Zoom level after 3 up-scrolls equals 175", "Zoom level after the following down-scroll equals 150"],
      automationConcepts: ["Mouse-wheel event dispatch", "Clamped numeric state assertion"],
    },
    validation: [{ kind: "equals", field: "zoomLevel", expected: 150 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
