import type { ChallengeDefinition } from "../../challenge-schema";

/** Moving Elements (spec category #24). All variants share the `dynamic-dom` engine component. */
export const movingElementsChallenges: ChallengeDefinition[] = [
  {
    id: "MOVING-001",
    title: "Deterministic Moving Banner — Click at Position 3",
    categoryId: "moving-elements",
    component: "dynamic-dom",
    variant: "deterministic-moving-banner",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A promo banner deterministically cycles through 3 fixed positions every 800ms, in a repeating, predictable order (1 \u2192 2 \u2192 3 \u2192 1\u2026).",
      dataNeeded: "None.",
      action: "Click the banner only while it is at Position 3.",
      expectedResult: "Clicking while at Position 3 registers the click; clicking during 1 or 2 must be avoided or explicitly waited past.",
      validationPoints: ["clickedAtPosition equals 3", "The automation must wait for the correct position rather than clicking blindly"],
      automationConcepts: ["Polling/waiting for an element attribute or position before acting", "Deterministic timing-based synchronization (not a fixed sleep)"],
    },
    validation: [{ kind: "equals", field: "clickedAtPosition", expected: 3 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "MOVING-002",
    title: "Moving Close Button That Settles Deterministically",
    categoryId: "moving-elements",
    component: "dynamic-dom",
    variant: "moving-close-button-settle",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "expert",
    frameworks: ["playwright"],
    accessibility: "intentional-defect",
    guidance: {
      whatItDoes: "An intrusive ad's \"\u2715\" close button relocates to a new corner every time the mouse gets within 40px of it, for exactly 5 dodges, then stops moving and stays put (deterministic, not infinite).",
      dataNeeded: "None.",
      action: "Attempt to click the close button; it will dodge up to 5 times, then click it once it stops.",
      expectedResult: "After the 5th dodge, the button remains stationary and the next click closes the ad.",
      validationPoints: ["dodgeCount equals 5 before the ad closes", "adClosed becomes true only after the button has stopped moving"],
      automationConcepts: ["Waiting for an element's position/bounding box to stabilize before clicking", "Handling intentionally-hostile automation obstacles safely and deterministically"],
      edgeCases: ["This pattern intentionally mimics a known bad UX/accessibility pattern (moving close buttons) \u2014 flagged as an intentional defect, not a platform bug."],
    },
    validation: [
      { kind: "equals", field: "dodgeCount", expected: 5 },
      { kind: "equals", field: "adClosed", expected: true },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
];
