import type { ChallengeDefinition } from "../../challenge-schema";

/** Network / API Testing (spec category #30). All variants share the `api-panel` engine component. */
export const networkApiTestingChallenges: ChallengeDefinition[] = [
  {
    id: "NETWORK-001",
    title: "GET Request — Inspect Response Body and Status",
    categoryId: "network-api-testing",
    component: "api-panel",
    variant: "get-list-products",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-products",
    difficulty: "easy",
    frameworks: ["postman", "rest-assured", "karate", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A REST playground panel sends `GET /api/lab/products` and displays the raw status code and JSON body.",
      dataNeeded: "None.",
      action: "Click \"Send GET /products\".",
      expectedResult: "Response status is 200 and the body contains an array of 5 seeded products.",
      validationPoints: ["responseStatus equals 200", "responseBody array length equals 5"],
      automationConcepts: ["Request/response inspection", "Status-code assertion", "JSON body schema/shape assertion"],
    },
    validation: [
      { kind: "equals", field: "lastStatus", expected: 200 },
      { kind: "equals", field: "lastProductCount", expected: 5 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "NETWORK-002",
    title: "POST Request — Create Resource and Verify 201 + Location",
    categoryId: "network-api-testing",
    component: "api-panel",
    variant: "post-create-product",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-products",
    difficulty: "medium",
    frameworks: ["postman", "rest-assured", "karate", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Sends `POST /api/lab/products` with a name and price to create a new product.",
      dataNeeded: "String name, e.g. \"Desk Lamp\"; number price, e.g. 24.99.",
      action: "Fill name \"Desk Lamp\" and price 24.99, then click \"Send POST /products\".",
      expectedResult: "Response status is 201, includes a `Location` header pointing at the new resource, and the body echoes the created product with a generated id.",
      validationPoints: ["responseStatus equals 201", "response body id is present and non-empty", "Location header path starts with /api/lab/products/"],
      automationConcepts: ["Request body construction", "Location-header assertion", "Resource-creation verification via follow-up GET"],
    },
    validation: [
      { kind: "equals", field: "lastStatus", expected: 201 },
      { kind: "truthy", field: "createdProductId" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "NETWORK-003",
    title: "PATCH Request — Partial Update",
    categoryId: "network-api-testing",
    component: "api-panel",
    variant: "patch-update-product",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-products",
    difficulty: "medium",
    frameworks: ["postman", "rest-assured", "karate", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Sends `PATCH /api/lab/products/p1` with only a `price` field, leaving `name`/`category` untouched.",
      dataNeeded: "Number price, e.g. 39.99.",
      action: "Set price to 39.99 and click \"Send PATCH /products/p1\".",
      expectedResult: "Response status is 200; the returned product has the new price but its original name and category unchanged.",
      validationPoints: ["responseStatus equals 200", "updated price equals 39.99", "name remains \"Wireless Keyboard\" (unchanged by PATCH)"],
      automationConcepts: ["Partial-update (PATCH) semantics vs full-replace (PUT)", "Verifying unaffected fields remain untouched"],
    },
    validation: [
      { kind: "equals", field: "lastStatus", expected: 200 },
      { kind: "equals", field: "patchedPrice", expected: 39.99 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "NETWORK-004",
    title: "DELETE Request — Remove Resource, Verify Subsequent 404",
    categoryId: "network-api-testing",
    component: "api-panel",
    variant: "delete-then-get",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-products",
    difficulty: "medium",
    frameworks: ["postman", "rest-assured", "karate", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Sends `DELETE /api/lab/products/p2`, then automatically re-fetches the same id to confirm it is gone.",
      dataNeeded: "None.",
      action: "Click \"Delete then verify\".",
      expectedResult: "DELETE returns 204; the follow-up GET on the same id returns 404.",
      validationPoints: ["deleteStatus equals 204", "followUpGetStatus equals 404"],
      automationConcepts: ["Delete-then-verify pattern", "204 No Content handling", "Chained request sequencing"],
    },
    validation: [
      { kind: "equals", field: "deleteStatus", expected: 204 },
      { kind: "equals", field: "followUpGetStatus", expected: 404 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "NETWORK-005",
    title: "Authenticated Endpoint — Bearer Token Required",
    categoryId: "network-api-testing",
    component: "api-panel",
    variant: "bearer-auth-endpoint",
    behavior: ["api"],
    environment: ["none"],
    dataSource: "api/lab-secure",
    difficulty: "hard",
    frameworks: ["postman", "rest-assured", "karate", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "`GET /api/lab/secure-report` requires header `Authorization: Bearer qa-lab-token`; without it the call is rejected.",
      dataNeeded: "None (token is pre-filled; try clearing it to see the failure case).",
      action: "Send the request without a token (expect 401), then with the correct token (expect 200).",
      expectedResult: "Missing/incorrect token yields 401; the exact token `qa-lab-token` yields 200 with the report body.",
      validationPoints: ["Unauthenticated call returns 401", "Authenticated call returns 200 with report field present"],
      automationConcepts: ["Authorization header construction", "Positive/negative auth-path testing", "Token-based API security testing"],
    },
    validation: [{ kind: "equals", field: "lastStatus", expected: 200 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
