import type { ChallengeDefinition } from "../../challenge-schema";

/** Popups (spec category #36). All variants share the `popup` engine component. */
export const popupsChallenges: ChallengeDefinition[] = [
  {
    id: "POPUP-001",
    title: "Cookie Consent Banner — Accept and Never Reappear",
    categoryId: "popups",
    component: "popup",
    variant: "cookie-consent-banner",
    behavior: ["delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A cookie-consent banner appears ~500ms after page load; accepting it stores the choice so it never reappears in this session.",
      dataNeeded: "None.",
      action: "Wait for the banner, click \"Accept\", then trigger a simulated page remount and confirm it does not reappear.",
      expectedResult: "Banner is dismissed immediately on Accept and stays dismissed across the simulated remount.",
      validationPoints: ["Banner is absent immediately after clicking Accept", "Banner remains absent after remount because the choice was persisted"],
      automationConcepts: ["Handling delayed-appearance overlays before interacting with the page", "Verifying a dismissal choice persists across a soft reload"],
    },
    validation: [{ kind: "equals", field: "cookieConsent", expected: "accepted" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-002",
    title: "Delayed Newsletter Popup with Auto-Close",
    categoryId: "popups",
    component: "popup",
    variant: "delayed-newsletter-popup",
    behavior: ["delayed"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A newsletter-signup popup appears after a 2-second delay and auto-closes on its own after 8 seconds if ignored, or immediately when explicitly closed.",
      dataNeeded: "None (or an email string if subscribing).",
      action: "Wait for the popup to appear, then close it via its \"X\" button before the 8-second auto-close.",
      expectedResult: "Manually closing removes the popup immediately; it does not reappear afterward in the same session.",
      validationPoints: ["Popup is absent before the 2-second delay elapses", "Popup is absent immediately after clicking its close control"],
      automationConcepts: ["Waiting for a delayed-appearance element before asserting its absence is meaningful", "Distinguishing manual dismissal from timeout-based auto-close"],
      edgeCases: ["Real browser-native permission dialogs (location/camera/microphone/notifications) cannot be scripted by web pages; this is a clearly labeled in-app simulation, not an attempt to control native UI."],
    },
    validation: [{ kind: "equals", field: "newsletterPopupOpen", expected: false }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-003",
    title: "Real Browser Geolocation Permission Prompt",
    categoryId: "popups",
    component: "popup",
    variant: "geolocation-permission-real",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "expert",
    frameworks: ["playwright", "selenium", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Get my location\" calls the REAL `navigator.geolocation.getCurrentPosition()` browser API \u2014 not a fake in-app dialog. In a normal browser this triggers the actual native permission popup near the address bar, which page JavaScript is deliberately forbidden from clicking (a security boundary, not a bug).",
      dataNeeded: "None from the UI \u2014 permission must be granted at the browser/automation-tool level, before the page even loads.",
      action: "Configure your automation tool to pre-grant geolocation permission for this origin (e.g. Playwright `browserContext.grantPermissions(['geolocation'], { origin })` + `context.setGeolocation({ latitude, longitude })`), THEN click \"Get my location\".",
      expectedResult: "With permission pre-granted, the call succeeds instantly with no visible prompt and shows real coordinates. Without pre-granted permission, most automated/headless browsers auto-deny and the page shows \"Location access denied.\"",
      validationPoints: ["locationPermission equals \"granted\" only when the real geolocation API call actually succeeds", "No amount of clicking inside the page can force this \u2014 it can only pass via correct automation-tool configuration"],
      automationConcepts: ["Browser-context-level permission grants (the ONLY real way to automate native permission prompts)", "Playwright grantPermissions/setGeolocation, Selenium Chrome prefs, Cypress navigator stubbing", "Distinguishing security-sandboxed native UI from anything a page can control"],
      edgeCases: ["This is intentionally the hardest difficulty in the platform \u2014 it cannot be solved by interacting with any element on this page at all, only by correct test-runner setup.", "If you already Allowed or Blocked location for this site in a previous visit, the browser remembers that choice and will NOT show the native popup again \u2014 the page detects this and tells you so. Reset the site's location permission (via the icon left of the address bar) to see the prompt again."],
    },
    validation: [{ kind: "equals", field: "locationPermission", expected: "granted" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 6,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-004",
    title: "Error Popup with Retry",
    categoryId: "popups",
    component: "popup",
    variant: "error-popup-retry",
    behavior: ["failure", "retry"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Save Changes\" deterministically fails the first time, popping up \"Failed to save changes\" with Retry/Cancel; Retry always succeeds on the second attempt.",
      dataNeeded: "None.",
      action: "Click \"Save Changes\" (see the error popup), then click \"Retry\" inside it.",
      expectedResult: "First attempt shows the error popup; clicking Retry closes it and shows a success confirmation.",
      validationPoints: ["Error popup appears after the first failed attempt", "saveStatus equals \"saved\" only after Retry succeeds"],
      automationConcepts: ["Deterministic fail-then-succeed popup flow", "Locating and clicking a button INSIDE an error popup", "Distinguishing an error popup from a toast/inline error"],
    },
    validation: [{ kind: "equals", field: "saveStatus", expected: "saved" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-005",
    title: "Enter-Value Popup (Native window.prompt)",
    categoryId: "popups",
    component: "popup",
    variant: "enter-value-prompt",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Set nickname\" triggers a REAL native `window.prompt(\"Enter your nickname\")` dialog \u2014 unlike the other popups here, this one is a genuine browser dialog, not an in-app simulation.",
      dataNeeded: "String nickname, e.g. \"QAChampion\".",
      action: "Handle the native prompt in your automation tool, type \"QAChampion\", and accept it.",
      expectedResult: "The page displays \"Nickname: QAChampion\" after the prompt is accepted with that text; dismissing/cancelling the prompt leaves the nickname unset.",
      validationPoints: ["nickname equals \"QAChampion\" only after accepting the prompt with that exact text", "Cancelling the prompt must not set any nickname"],
      automationConcepts: ["Native dialog handling APIs (Playwright page.on('dialog'), Selenium Alert.sendKeys, Cypress cy.window().then + stub)", "Difference between accept-with-text vs dismiss on window.prompt", "Framework-specific auto-dismiss defaults (Cypress auto-dismisses window.prompt unless stubbed \u2014 a common real-world gotcha)"],
    },
    validation: [{ kind: "equals", field: "nickname", expected: "QAChampion" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-006",
    title: "Accept / Decline Popup — Terms Update",
    categoryId: "popups",
    component: "popup",
    variant: "accept-decline-popup",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A \"Terms Update\" popup requires an explicit Accept or Decline; Decline keeps the account restricted, Accept unlocks full access.",
      dataNeeded: "None.",
      action: "Click \"Decline\" first (observe restricted state), reopen the popup, then click \"Accept\".",
      expectedResult: "Declining shows \"Access restricted until you accept\"; accepting shows \"Full access granted\".",
      validationPoints: ["Declining leaves termsAccepted false and shows the restricted message", "Accepting sets termsAccepted true and shows full access"],
      automationConcepts: ["Binary-choice popup testing (both branches)", "Re-opening a popup after a non-terminal choice"],
    },
    validation: [{ kind: "equals", field: "termsAccepted", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-007",
    title: "Network / Connection-Lost Popup",
    categoryId: "popups",
    component: "popup",
    variant: "network-lost-popup",
    behavior: ["failure", "retry"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Sync Data\" deterministically shows a \"Connection lost. Retry?\" popup on the first attempt (simulating a dropped network), and succeeds on Retry.",
      dataNeeded: "None.",
      action: "Click \"Sync Data\", observe the connection-lost popup, then click \"Retry\" inside it.",
      expectedResult: "First sync always shows the network popup; Retry always succeeds and shows \"Data synced\".",
      validationPoints: ["Network popup appears on the first sync attempt", "syncStatus equals \"synced\" only after Retry"],
      automationConcepts: ["Simulated offline/connection-loss UX pattern", "Retry-popup interaction distinct from toast-based retry (compare to BUTTON-005/AJAX-002)"],
    },
    validation: [{ kind: "equals", field: "syncStatus", expected: "synced" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-008",
    title: "Real Browser Notification Permission Prompt",
    categoryId: "popups",
    component: "popup",
    variant: "notification-permission-real",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "expert",
    frameworks: ["playwright", "selenium", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Enable notifications\" calls the REAL `Notification.requestPermission()` browser API. In a normal browser this triggers the actual native \"site wants to send notifications\" popup, which page JavaScript cannot click \u2014 by design, for the exact same security reasons as geolocation.",
      dataNeeded: "None from the UI \u2014 permission must be pre-granted at the browser/automation-tool level.",
      action: "Configure your automation tool to pre-grant the `notifications` permission for this origin (e.g. Playwright `browserContext.grantPermissions(['notifications'], { origin })`), THEN click \"Enable notifications\".",
      expectedResult: "With permission pre-granted, `Notification.permission` resolves to \"granted\" with no visible prompt. Without it, automated/headless browsers auto-deny by default.",
      validationPoints: ["notificationPermission equals \"granted\" only when the real Notification API genuinely reports granted", "Clicking anything in the page cannot substitute for correct browser-context configuration"],
      automationConcepts: ["Notification.permission / Notification.requestPermission() real API", "Browser-context permission grants (same mechanism family as geolocation, camera, microphone)", "Why these prompts are intentionally unreachable from in-page automation"],
      edgeCases: ["If you already Allowed or Blocked notifications for this site previously, the browser remembers that choice and will NOT show the native popup again \u2014 the page detects and displays this. Reset the site's notification permission (via the icon left of the address bar) to see the prompt again."],
    },
    validation: [{ kind: "equals", field: "notificationPermission", expected: "granted" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-009",
    title: "Auto-Closing Info Popup",
    categoryId: "popups",
    component: "popup",
    variant: "auto-closing-info-popup",
    behavior: ["delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Show tip\" opens an info popup that closes itself automatically after 3 seconds if left alone, or immediately if manually dismissed.",
      dataNeeded: "None.",
      action: "Click \"Show tip\" and either wait 3+ seconds without interacting, or click its close button early.",
      expectedResult: "The popup disappears on its own after 3 seconds even with zero user interaction, and disappears immediately if closed manually before that.",
      validationPoints: ["infoPopupClosed becomes true either via the 3s auto-close timer or a manual close click", "Popup is not present in the DOM once closed, by either path"],
      automationConcepts: ["Waiting for a time-based auto-dismiss instead of polling forever", "Race between manual action and a running timer"],
    },
    validation: [{ kind: "equals", field: "infoPopupClosed", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-010",
    title: "Nested Popup — Type-to-Confirm Account Deletion",
    categoryId: "popups",
    component: "popup",
    variant: "nested-popup",
    behavior: ["static"],
    environment: ["modal"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Delete Account\" opens a warning popup; clicking \"Continue\" opens a SECOND popup stacked on top requiring the tester to type the exact word \"DELETE\" before the action is allowed.",
      dataNeeded: "The exact text \"DELETE\".",
      action: "Click \"Delete Account\" \u2192 \"Continue\", type \"DELETE\" in the nested popup, then click \"Confirm Deletion\".",
      expectedResult: "\"Confirm Deletion\" stays disabled until the typed text exactly matches \"DELETE\"; confirming closes both popups and shows a final confirmation.",
      validationPoints: ["Confirm button is disabled for any text other than exactly \"DELETE\"", "accountDeletionConfirmed is true only after confirming with the correct text"],
      automationConcepts: ["Two-level popup stack scoping (locator must target the topmost popup)", "Exact-match text-gated action enablement", "High-risk-action confirmation pattern testing"],
    },
    validation: [{ kind: "equals", field: "accountDeletionConfirmed", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-011",
    title: "Native window.alert() Popup",
    categoryId: "popups",
    component: "popup",
    variant: "native-alert",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Show browser alert\" calls the REAL native `window.alert(\"...\")` \u2014 the actual browser-chrome popup (not a styled `<div>`), which blocks all page interaction until dismissed.",
      dataNeeded: "None.",
      action: "Click \"Show browser alert\" and accept/dismiss the native alert in your automation tool.",
      expectedResult: "The alert blocks the page until dismissed; once dismissed, the page confirms it was shown.",
      validationPoints: ["alertDismissed is true only after the native alert has actually been accepted", "No page element can be interacted with while the native alert is open"],
      automationConcepts: ["Native dialog event handling (Playwright page.on('dialog'), Selenium driver.switchTo().alert(), Cypress auto-accepts window.alert by default)", "Distinguishing a native alert from an in-app styled popup"],
    },
    validation: [{ kind: "equals", field: "alertDismissed", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "POPUP-012",
    title: "Native Print Dialog (window.print())",
    categoryId: "popups",
    component: "popup",
    variant: "native-print-dialog",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "expert",
    frameworks: ["playwright", "selenium", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"Print Invoice\" calls the REAL `window.print()` API, which opens the browser's native, OS-level print dialog \u2014 a UI surface entirely outside the DOM/CDP automation surface.",
      dataNeeded: "None.",
      action: "Click \"Print Invoice\". Do not attempt to interact with the native print dialog itself \u2014 instead, verify from your test code that `window.print` was actually invoked.",
      expectedResult: "The standard, correct automation pattern is to stub/spy on `window.print` BEFORE clicking (e.g. `page.addInitScript` or `cy.window().then(w => cy.stub(w, 'print'))`) and assert the stub was called, since the real dialog cannot be driven programmatically.",
      validationPoints: ["printTriggered is true only after window.print() is actually invoked", "This challenge cannot be completed by trying to find/click elements inside the native print dialog \u2014 there are none exposed to the DOM"],
      automationConcepts: ["Stubbing/spying on a native browser API instead of interacting with its UI", "Recognizing when a browser surface is intentionally outside automation reach", "print-preview-triggering verification pattern"],
    },
    validation: [{ kind: "equals", field: "printTriggered", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
