import type { ChallengeDefinition } from "../../challenge-schema";

/** Real Applications (spec #49, Phase 10). Complete, multi-step mini-app missions using the `mission` engine component. */
export const realApplicationsChallenges: ChallengeDefinition[] = [
  {
    id: "ECOM-001",
    title: "E-Commerce Checkout \u2014 Cart to Order Confirmation",
    categoryId: "ecommerce",
    component: "mission",
    variant: "ecommerce-checkout",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/ecommerce-checkout",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A complete real-world checkout flow across 4 steps: Cart (editable quantities + coupon), Shipping (address form), Payment (Card/UPI/COD), and Confirmation (order ID + charged total) \u2014 combining many component types into one realistic end-to-end journey instead of an isolated widget.",
      dataNeeded: "Shipping details: Full name \"Asha Verma\", Address \"221B MG Road\", City \"Bengaluru\", Postal code \"560001\", Phone \"9876543210\". Coupon code \"SAVE10\".",
      action: "In the Cart step, set \"Wireless Mouse\" quantity to 2 (leave Keyboard and USB-C Hub at 1), apply coupon \"SAVE10\", then proceed to Shipping and fill in the exact details above, then choose \"Card\" as the payment method and place the order.",
      expectedResult: "Cart total becomes $130.50 after the 10% coupon discount ((2\u00d7$25 + $65 + $30) \u00d7 0.9). After placing the order, a confirmation screen shows an Order ID and the shipping details entered.",
      validationPoints: ["orderTotal equals 130.5", "shippingFullName equals \"Asha Verma\"", "paymentMethod equals \"card\"", "orderPlaced is truthy"],
      automationConcepts: ["Multi-step wizard navigation (Next/Back gating on validity)", "Derived total recalculation across quantity + coupon changes", "End-to-end order journey spanning cart, form, and payment components", "Asserting a final confirmation screen after a multi-step flow"],
    },
    validation: [
      { kind: "equals", field: "orderTotal", expected: 130.5 },
      { kind: "equals", field: "shippingFullName", expected: "Asha Verma" },
      { kind: "equals", field: "paymentMethod", expected: "card" },
      { kind: "truthy", field: "orderPlaced" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 8,
    resettable: true,
    isActive: true,
  },
  {
    id: "BANK-001",
    title: "Banking \u2014 OTP-Verified Fund Transfer",
    categoryId: "banking",
    component: "mission",
    variant: "banking-fund-transfer",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/banking-transfer",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A realistic fund-transfer flow: pick a from-account and beneficiary, enter an amount (with min/available-balance validation), review the summary, receive a test-only OTP (displayed directly \u2014 same convention as the Auth Lab, since automation can't read real SMS), verify it, and see the account balance update.",
      dataNeeded: "Transfer $1,500 from the Savings account to beneficiary Ravi Kumar.",
      action: "Select \"Savings\" as the from-account and \"Ravi Kumar\" as the beneficiary, enter amount 1500, continue to review, click \"Send OTP\", copy the displayed OTP into the verification field, then click \"Verify & Transfer\".",
      expectedResult: "The transfer completes and the Savings account's new balance shows $3,500 (5000 - 1500). Entering the wrong OTP does not complete the transfer.",
      validationPoints: ["transferAmount equals 1500", "toBeneficiary equals \"Ravi Kumar\"", "newFromBalance equals 3500", "otpVerified is truthy"],
      automationConcepts: ["Reading a test-only OTP from the DOM instead of SMS/email", "Amount validation against a dynamic available-balance constraint", "Multi-step review-then-confirm transactional flow", "Post-transaction balance recalculation assertion"],
    },
    validation: [
      { kind: "equals", field: "transferAmount", expected: 1500 },
      { kind: "equals", field: "toBeneficiary", expected: "Ravi Kumar" },
      { kind: "equals", field: "newFromBalance", expected: 3500 },
      { kind: "truthy", field: "otpVerified" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 6,
    resettable: true,
    isActive: true,
  },
  {
    id: "TRAVEL-001",
    title: "Travel \u2014 Search, Sort, and Book the Cheapest Flight",
    categoryId: "travel",
    component: "mission",
    variant: "travel-flight-booking",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/flight-search",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 5-step flight booking journey: search by route/date, sort and select from real results, enter passenger details, pay, and get a PNR confirmation \u2014 exercising sorting, selection, form-filling, and a multi-step wizard together.",
      dataNeeded: "Route Bengaluru \u2192 Delhi, any future date. Passenger \"Rohit Sharma\", age 29, Window seat. Pay via UPI \"rohit@upi\".",
      action: "Search Bengaluru to Delhi for any date, sort flight results by price ascending, select the cheapest flight, fill passenger name \"Rohit Sharma\" / age 29 / seat \"Window\", choose UPI payment with ID \"rohit@upi\", then confirm the booking.",
      expectedResult: "Sorting ascending puts \"Vistara UK-811\" ($110) on top \u2014 selecting it and completing the flow shows a PNR confirmation screen.",
      validationPoints: ["selectedFlightNumber equals \"UK-811\"", "passengerName equals \"Rohit Sharma\"", "seatPreference equals \"window\"", "paymentMethod equals \"upi\"", "bookingConfirmed is truthy"],
      automationConcepts: ["Sort-then-select from a results table", "Conditional field rendering based on a prior radio selection (UPI ID only shown for UPI)", "5-step wizard state carried across screens", "Final booking-confirmation assertion (PNR)"],
    },
    validation: [
      { kind: "equals", field: "selectedFlightNumber", expected: "UK-811" },
      { kind: "equals", field: "passengerName", expected: "Rohit Sharma" },
      { kind: "equals", field: "seatPreference", expected: "window" },
      { kind: "equals", field: "paymentMethod", expected: "upi" },
      { kind: "truthy", field: "bookingConfirmed" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 7,
    resettable: true,
    isActive: true,
  },
];
