import type { ChallengeDefinition } from "../../challenge-schema";

/** Real Applications (spec #49, Phase 10). Complete, multi-step mini-app missions using the `mission` engine component. */
export const realApplicationsChallenges: ChallengeDefinition[] = [
  {
    id: "ECOM-001",
    title: "E-Commerce \u2014 AwesomeMart, a Real Separate Storefront",
    categoryId: "ecommerce",
    component: "mission",
    variant: "ecommerce-real-site",
    behavior: ["static", "validated-on-submit"],
    environment: ["new-tab"],
    dataSource: "static/awesomemart-storefront",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"AwesomeMart\" is a genuine, separate multi-page e-commerce site (real product grid with search, category AND price-range filters, a working wishlist, cart, checkout, order tracking, and order cancellation) that opens in its OWN browser tab \u2014 nothing is embedded on this page. Checkout deliberately uses several classic hard-to-automate patterns: card details live inside a real embedded <iframe> (like a real payment provider), a discount code is hidden inside a real shadow-DOM widget, City is a dependent dropdown driven by State, delivery date is a real min/max-constrained date picker, and gift-wrap is a radio that reveals a dropdown. As you shop, every milestone is reported back to this page in real time over a BroadcastChannel, and THIS page's self-check validates what actually happened on that separate site.",
      dataNeeded: "AwesomeMart's \"Footwear\" category has 6 different shoe brands at different prices. Filter by price between $70 and $80 \u2014 only \"Reebok Classic Move\" ($72.50) matches. Wishlist it, add it to cart from the wishlist, checkout (any address, any State/City, any valid delivery date), then CANCEL that order. Go back, pick a different shoe \u2014 \"Bata Everyday Walk\" ($45.00) \u2014 add it to cart, and checkout with Cash on Delivery, again picking a valid delivery date.",
      action: "Open AwesomeMart. Filter to the \"Footwear\" category and set the price range to 70\u201380 so only \"Reebok Classic Move\" shows; \u2665 wishlist it. Open the Wishlist page and click \"Add to Cart\" there. Go to Cart \u2192 Checkout, fill the address, choose any State (this drives the City dropdown), choose any valid delivery date (the field enforces the allowed range), pick any payment method, place the order \u2014 then on the order page click \"Cancel Order\". Go back, find \"Bata Everyday Walk\", add it to cart, checkout again with a valid delivery date, choose \"Cash on Delivery\", and place that order.",
      expectedResult: "The Wishlist page lists your wishlisted shoe with its own \"Add to Cart\" button. The first order shows as \"Cancelled\" in this page's order log. A second, active order for \"Bata Everyday Walk\" paid by Cash on Delivery appears as \"Active\" with a valid delivery date recorded.",
      validationPoints: ["favoritedProductName equals \"Reebok Classic Move\"", "firstOrderCancelled is truthy", "finalOrderPlaced is truthy", "finalOrderPaymentMethod equals \"cod\"", "finalOrderProductNames contains \"Bata Everyday Walk\"", "finalOrderDeliveryDate is truthy (a real date within the allowed min/max window was chosen)"],
      automationConcepts: [
        "Real cross-tab / cross-application integration testing (BroadcastChannel)",
        "Switching into a real payment <iframe> to fill card fields (frameLocator/switchTo().frame())",
        "Piercing a real open shadow root to read a hidden discount code",
        "Dependent/cascading State \u2192 City dropdown (must select State before City is enabled)",
        "A real min/max-constrained date picker (delivery date)",
        "Radio-reveals-dropdown (gift wrap) combined with an unrelated cascading dropdown on the same form",
        "Price-range + category filtering to isolate one item among several similar ones",
        "Order placement THEN cancellation, followed by a second successful order \u2014 asserting the correct final state, not just the first event received",
      ],
      edgeCases: ["Placing a second order after cancelling the first must NOT be confused with the cancelled one \u2014 the self-check specifically checks the LAST non-cancelled order, so cancelling must genuinely happen before the second order is placed.", "The City dropdown stays disabled until a State is chosen \u2014 selecting City first is not possible, by design."],
    },
    validation: [
      { kind: "equals", field: "favoritedProductName", expected: "Reebok Classic Move" },
      { kind: "truthy", field: "firstOrderCancelled" },
      { kind: "truthy", field: "finalOrderPlaced" },
      { kind: "equals", field: "finalOrderPaymentMethod", expected: "cod" },
      { kind: "contains", field: "finalOrderProductNames", expected: "Bata Everyday Walk" },
      { kind: "truthy", field: "finalOrderDeliveryDate" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 10,
    resettable: true,
    isActive: true,
  },
  {
    id: "BANK-001",
    title: "Banking \u2014 OTP-Verified Fund Transfer",
    categoryId: "banking",
    component: "mission",
    variant: "banking-fund-transfer",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/banking-transfer",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A realistic fund-transfer flow: pick a from-account and beneficiary, enter an amount (with min/available-balance validation), review the summary, receive a test-only OTP (displayed directly \u2014 same convention as the Auth Lab, since automation can't read real SMS), verify it, and see the account balance update.",
      dataNeeded: "Transfer $1,500 from the Savings account to beneficiary Ravi Kumar.",
      action: "Select \"Savings\" as the from-account and \"Ravi Kumar\" as the beneficiary, enter amount 1500, continue to review, click \"Send OTP\", copy the displayed OTP into the verification field, then click \"Verify & Transfer\".",
      expectedResult: "The transfer completes and the Savings account's new balance shows $3,500 (5000 - 1500). Entering the wrong OTP does not complete the transfer.",
      validationPoints: ["transferAmount equals 1500", "toBeneficiary equals \"Ravi Kumar\"", "newFromBalance equals 3500", "otpVerified is truthy"],
      automationConcepts: ["Reading a test-only OTP from the DOM instead of SMS/email", "Amount validation against a dynamic available-balance constraint", "Multi-step review-then-confirm transactional flow", "Post-transaction balance recalculation assertion"],
    },
    validation: [
      { kind: "equals", field: "transferAmount", expected: 1500 },
      { kind: "equals", field: "toBeneficiary", expected: "Ravi Kumar" },
      { kind: "equals", field: "newFromBalance", expected: 3500 },
      { kind: "truthy", field: "otpVerified" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 6,
    resettable: true,
    isActive: true,
  },
  {
    id: "TRAVEL-001",
    title: "Travel \u2014 Search, Sort, and Book the Cheapest Flight",
    categoryId: "travel",
    component: "mission",
    variant: "travel-flight-booking",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/flight-search",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 5-step flight booking journey: search by route/date, sort and select from real results, enter passenger details, pay, and get a PNR confirmation \u2014 exercising sorting, selection, form-filling, and a multi-step wizard together.",
      dataNeeded: "Route Bengaluru \u2192 Delhi, any future date. Passenger \"Rohit Sharma\", age 29, Window seat. Pay via UPI \"rohit@upi\".",
      action: "Search Bengaluru to Delhi for any date, sort flight results by price ascending, select the cheapest flight, fill passenger name \"Rohit Sharma\" / age 29 / seat \"Window\", choose UPI payment with ID \"rohit@upi\", then confirm the booking.",
      expectedResult: "Sorting ascending puts \"Vistara UK-811\" ($110) on top \u2014 selecting it and completing the flow shows a PNR confirmation screen.",
      validationPoints: ["selectedFlightNumber equals \"UK-811\"", "passengerName equals \"Rohit Sharma\"", "seatPreference equals \"window\"", "paymentMethod equals \"upi\"", "bookingConfirmed is truthy"],
      automationConcepts: ["Sort-then-select from a results table", "Conditional field rendering based on a prior radio selection (UPI ID only shown for UPI)", "5-step wizard state carried across screens", "Final booking-confirmation assertion (PNR)"],
    },
    validation: [
      { kind: "equals", field: "selectedFlightNumber", expected: "UK-811" },
      { kind: "equals", field: "passengerName", expected: "Rohit Sharma" },
      { kind: "equals", field: "seatPreference", expected: "window" },
      { kind: "equals", field: "paymentMethod", expected: "upi" },
      { kind: "truthy", field: "bookingConfirmed" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 7,
    resettable: true,
    isActive: true,
  },
];
