import type { ChallengeDefinition } from "../../challenge-schema";

/** Real Applications (spec #49, Phase 10). Complete, multi-step mini-app missions using the `mission` engine component. */
export const realApplicationsChallenges: ChallengeDefinition[] = [
  {
    id: "ECOM-001",
    title: "E-Commerce \u2014 AwesomeMart, a Real Separate Storefront",
    categoryId: "ecommerce",
    component: "mission",
    variant: "ecommerce-real-site",
    behavior: ["static", "validated-on-submit"],
    environment: ["new-tab"],
    dataSource: "static/awesomemart-storefront",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "\"AwesomeMart\" is a genuine, separate multi-page e-commerce site (real product grid with search + category filters, favorites, cart, checkout, and order tracking) that opens in its OWN browser tab \u2014 nothing is embedded on this page. As you shop on AwesomeMart, every milestone (favoriting, cart changes, placing the order, delivery status) is reported back to this page in real time over a BroadcastChannel, and THIS page's self-check validates what actually happened on that separate site.",
      dataNeeded: "Favorite \"Wireless Headphones\". Add \"Wireless Headphones\" and \"Smart Watch\" to your cart (2 line items total). Checkout with City \"Bengaluru\" and Card payment. Advance the order to \"Delivered\".",
      action: "Click \"Open AwesomeMart in a new tab\". On AwesomeMart: search or browse to \u2665 favorite \"Wireless Headphones\", add it and \"Smart Watch\" to your cart, go to the cart, proceed to checkout, fill the address with City \"Bengaluru\", choose \"Card\" as payment, place the order, then on the order-tracking page click \"Advance to next status\" repeatedly until the status reaches \"Delivered\".",
      expectedResult: "This page's \"Live progress from AwesomeMart\" panel updates in real time as you act on the other tab, ending with: favorited product \"Wireless Headphones\", 2 cart line items, an order placed for Bengaluru paid by card, and delivery status \"Delivered\".",
      validationPoints: ["favoritedProductName equals \"Wireless Headphones\"", "cartItemCount equals 2", "shippingCity equals \"Bengaluru\"", "paymentMethod equals \"card\"", "orderPlaced is truthy", "deliveryStatus equals \"Delivered\""],
      automationConcepts: ["Real cross-tab / cross-application integration testing (BroadcastChannel)", "Driving a second real browser tab from a Playwright/Selenium test and asserting on a receiving page", "A genuinely separate multi-page site (own routes, own state) instead of an in-page simulation", "Milestone-based event reporting instead of polling"],
      edgeCases: ["The progress panel only updates once AwesomeMart actually posts an event \u2014 closing the AwesomeMart tab without completing an action leaves that field unset, so partial attempts correctly fail the self-check."],
    },
    validation: [
      { kind: "equals", field: "favoritedProductName", expected: "Wireless Headphones" },
      { kind: "equals", field: "cartItemCount", expected: 2 },
      { kind: "equals", field: "shippingCity", expected: "Bengaluru" },
      { kind: "equals", field: "paymentMethod", expected: "card" },
      { kind: "truthy", field: "orderPlaced" },
      { kind: "equals", field: "deliveryStatus", expected: "Delivered" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 10,
    resettable: true,
    isActive: true,
  },
  {
    id: "BANK-001",
    title: "Banking \u2014 OTP-Verified Fund Transfer",
    categoryId: "banking",
    component: "mission",
    variant: "banking-fund-transfer",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/banking-transfer",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A realistic fund-transfer flow: pick a from-account and beneficiary, enter an amount (with min/available-balance validation), review the summary, receive a test-only OTP (displayed directly \u2014 same convention as the Auth Lab, since automation can't read real SMS), verify it, and see the account balance update.",
      dataNeeded: "Transfer $1,500 from the Savings account to beneficiary Ravi Kumar.",
      action: "Select \"Savings\" as the from-account and \"Ravi Kumar\" as the beneficiary, enter amount 1500, continue to review, click \"Send OTP\", copy the displayed OTP into the verification field, then click \"Verify & Transfer\".",
      expectedResult: "The transfer completes and the Savings account's new balance shows $3,500 (5000 - 1500). Entering the wrong OTP does not complete the transfer.",
      validationPoints: ["transferAmount equals 1500", "toBeneficiary equals \"Ravi Kumar\"", "newFromBalance equals 3500", "otpVerified is truthy"],
      automationConcepts: ["Reading a test-only OTP from the DOM instead of SMS/email", "Amount validation against a dynamic available-balance constraint", "Multi-step review-then-confirm transactional flow", "Post-transaction balance recalculation assertion"],
    },
    validation: [
      { kind: "equals", field: "transferAmount", expected: 1500 },
      { kind: "equals", field: "toBeneficiary", expected: "Ravi Kumar" },
      { kind: "equals", field: "newFromBalance", expected: 3500 },
      { kind: "truthy", field: "otpVerified" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 6,
    resettable: true,
    isActive: true,
  },
  {
    id: "TRAVEL-001",
    title: "Travel \u2014 Search, Sort, and Book the Cheapest Flight",
    categoryId: "travel",
    component: "mission",
    variant: "travel-flight-booking",
    behavior: ["static", "validated-on-submit"],
    environment: ["none"],
    dataSource: "static/flight-search",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 5-step flight booking journey: search by route/date, sort and select from real results, enter passenger details, pay, and get a PNR confirmation \u2014 exercising sorting, selection, form-filling, and a multi-step wizard together.",
      dataNeeded: "Route Bengaluru \u2192 Delhi, any future date. Passenger \"Rohit Sharma\", age 29, Window seat. Pay via UPI \"rohit@upi\".",
      action: "Search Bengaluru to Delhi for any date, sort flight results by price ascending, select the cheapest flight, fill passenger name \"Rohit Sharma\" / age 29 / seat \"Window\", choose UPI payment with ID \"rohit@upi\", then confirm the booking.",
      expectedResult: "Sorting ascending puts \"Vistara UK-811\" ($110) on top \u2014 selecting it and completing the flow shows a PNR confirmation screen.",
      validationPoints: ["selectedFlightNumber equals \"UK-811\"", "passengerName equals \"Rohit Sharma\"", "seatPreference equals \"window\"", "paymentMethod equals \"upi\"", "bookingConfirmed is truthy"],
      automationConcepts: ["Sort-then-select from a results table", "Conditional field rendering based on a prior radio selection (UPI ID only shown for UPI)", "5-step wizard state carried across screens", "Final booking-confirmation assertion (PNR)"],
    },
    validation: [
      { kind: "equals", field: "selectedFlightNumber", expected: "UK-811" },
      { kind: "equals", field: "passengerName", expected: "Rohit Sharma" },
      { kind: "equals", field: "seatPreference", expected: "window" },
      { kind: "equals", field: "paymentMethod", expected: "upi" },
      { kind: "truthy", field: "bookingConfirmed" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 7,
    resettable: true,
    isActive: true,
  },
];
