import type { ChallengeDefinition } from "../../challenge-schema";

/** Scroll Behaviors (spec category #21). All variants share the `scroll-area` engine component. */
export const scrollBehaviorsChallenges: ChallengeDefinition[] = [
  {
    id: "SCROLL-001",
    title: "Scroll-to-Top Button Appears After Threshold",
    categoryId: "scroll-behaviors",
    component: "scroll-area",
    variant: "scroll-to-top-threshold",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A long report page shows a floating \"Back to top\" button only after scrolling past 400px, and it scrolls smoothly to the top when clicked.",
      dataNeeded: "None.",
      action: "Scroll the panel down past 400px, click \"Back to top\".",
      expectedResult: "The button is invisible near the top, appears after the threshold, and scrolling resets to position 0.",
      validationPoints: ["Button is not present/visible before the threshold", "scrollTop equals 0 after clicking the button"],
      automationConcepts: ["Scroll-position-driven visibility assertions", "scrollTo/scrollIntoView verification"],
    },
    validation: [{ kind: "equals", field: "scrollTop", expected: 0 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "SCROLL-002",
    title: "Independent Nested Scroll Containers",
    categoryId: "scroll-behaviors",
    component: "scroll-area",
    variant: "nested-scroll-containers",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A page has an outer scrollable page area and an inner scrollable \"Activity Log\" panel; scrolling inside the panel must not scroll the outer page.",
      dataNeeded: "None.",
      action: "Scroll inside the Activity Log panel to its bottom.",
      expectedResult: "The panel's internal scroll position reaches its max while the outer page scroll position remains unchanged.",
      validationPoints: ["Inner panel scrollTop reaches its scrollHeight-clientHeight", "Outer page scrollY is unaffected by scrolling inside the panel"],
      automationConcepts: ["Scoped scroll-event testing", "Distinguishing nested scroll containers from the document scroll"],
    },
    validation: [{ kind: "truthy", field: "innerPanelScrolledToEnd" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "SCROLL-003",
    title: "Sticky Header While Scrolling",
    categoryId: "scroll-behaviors",
    component: "scroll-area",
    variant: "sticky-header",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A table's column header row stays pinned to the top of its scroll container while the body scrolls underneath it.",
      dataNeeded: "None.",
      action: "Scroll the table body down and confirm the header row stays visible and correctly aligned.",
      expectedResult: "The header remains at the top of the viewport/container with `position: sticky` throughout the scroll.",
      validationPoints: ["Header's bounding box top offset stays constant while scrolling the body", "Header remains present in the accessibility tree at all scroll positions"],
      automationConcepts: ["Bounding-box position assertions across scroll events", "CSS position:sticky behavior verification"],
    },
    validation: [{ kind: "truthy", field: "headerStuckAtTop" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
];
