import type { ChallengeDefinition } from "../../challenge-schema";

/** Shadow DOM (spec category #29). All variants share the `shadow-dom` engine component. */
export const shadowDomChallenges: ChallengeDefinition[] = [
  {
    id: "SHADOW-001",
    title: "Text Input Inside Open Shadow DOM",
    categoryId: "shadow-dom",
    component: "shadow-dom",
    variant: "input-in-open-shadow-dom",
    behavior: ["static"],
    environment: ["shadow-dom"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A custom element (`<qa-coupon-field>`) attaches an OPEN shadow root containing a coupon-code input, invisible to normal CSS/DOM queries against the light DOM.",
      dataNeeded: "String, e.g. \"SAVE20\".",
      action: "Pierce the shadow root and type \"SAVE20\" into the coupon field.",
      expectedResult: "The value is accepted and the parent page shows \"Coupon applied: SAVE20\".",
      validationPoints: ["Element cannot be found by a plain top-level document query, only via shadowRoot traversal", "Applied coupon equals \"SAVE20\""],
      automationConcepts: ["Piercing open shadow roots (element.shadowRoot)", "Framework-specific shadow-DOM-aware locators"],
    },
    validation: [{ kind: "equals", field: "appliedCoupon", expected: "SAVE20" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "SHADOW-002",
    title: "Nested Shadow DOM — Shadow Root Inside a Shadow Root",
    categoryId: "shadow-dom",
    component: "shadow-dom",
    variant: "nested-shadow-dom",
    behavior: ["static"],
    environment: ["shadow-dom"],
    dataSource: "static/none",
    difficulty: "nightmare",
    frameworks: ["playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An outer custom element's shadow root contains a second custom element which itself attaches its own open shadow root containing the actual \"Confirm\" button.",
      dataNeeded: "None.",
      action: "Pierce two levels of shadow DOM and click the innermost \"Confirm\" button.",
      expectedResult: "A confirmation badge appears on the main page.",
      validationPoints: ["Confirmation only registers after piercing both shadow boundaries", "Button is unreachable via a single-level shadowRoot query"],
      automationConcepts: ["Recursive/nested shadow-root traversal", "Locator strategies for deeply encapsulated web components"],
    },
    validation: [{ kind: "equals", field: "nestedShadowConfirmed", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 5,
    resettable: true,
    isActive: true,
  },
];
