import type { ChallengeDefinition } from "../../challenge-schema";

/** Sliders & Carousels (spec category #20). Uses the `slider` and `carousel` engine components. */
export const slidersCarouselsChallenges: ChallengeDefinition[] = [
  {
    id: "SLIDER-001",
    title: "Volume Slider with Keyboard Support",
    categoryId: "sliders-carousels",
    component: "slider",
    variant: "single-slider-keyboard",
    behavior: ["keyboard-controlled"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A single volume slider (range 0-100) that supports both mouse drag and Arrow-key adjustment in steps of 5.",
      dataNeeded: "None.",
      action: "Focus the slider and press ArrowRight 4 times, then ArrowLeft once.",
      expectedResult: "Value increases by 5 per ArrowRight (to 20 from 0) and decreases by 5 per ArrowLeft (to 15).",
      validationPoints: ["Value equals 15 after the described key sequence", "role=\"slider\" with correct aria-valuenow is present"],
      automationConcepts: ["Keyboard-driven slider interaction", "ARIA slider role/value assertions"],
    },
    validation: [{ kind: "equals", field: "volume", expected: 15 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "SLIDER-002",
    title: "Dual-Handle Price Range Slider",
    categoryId: "sliders-carousels",
    component: "slider",
    variant: "dual-range-slider",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "hard",
    frameworks: ["playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A dual-handle price filter (range $0-$1000) where the min handle cannot cross the max handle and vice versa.",
      dataNeeded: "Two bounds, e.g. min=200, max=600.",
      action: "Drag/set the min handle to 200 and the max handle to 600, then try dragging min past 600.",
      expectedResult: "Min and max settle at 200/600; attempting to drag min beyond max clamps it to just below max instead of crossing over.",
      validationPoints: ["minPrice <= maxPrice is always true", "Final values equal 200 and 600 respectively"],
      automationConcepts: ["Dual-handle constraint testing", "Clamped-value boundary assertions"],
    },
    validation: [
      { kind: "equals", field: "minPrice", expected: 200 },
      { kind: "equals", field: "maxPrice", expected: 600 },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "CAROUSEL-001",
    title: "Product Carousel — Next/Previous and Dots",
    categoryId: "sliders-carousels",
    component: "carousel",
    variant: "carousel-navigation",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/featured-products",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 4-slide featured-products carousel with Next/Previous arrows, clickable dots, and auto-play that pauses on hover.",
      dataNeeded: "None.",
      action: "Click Next twice, then click the first dot to jump back to slide 1.",
      expectedResult: "Active slide index updates to 3 after two Next clicks, then to 1 after clicking the first dot.",
      validationPoints: ["activeSlide equals 1 (1-indexed) after clicking the first dot", "Auto-play stops while the mouse hovers the carousel"],
      automationConcepts: ["Carousel index-state assertions", "Verifying auto-play pause-on-hover behavior"],
    },
    validation: [{ kind: "equals", field: "activeSlide", expected: 1 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
