import type { ChallengeDefinition } from "../../challenge-schema";

/** Tables & Grids (spec category #8). All variants share the `table` engine component. */
export const tablesGridsChallenges: ChallengeDefinition[] = [
  {
    id: "TABLE-001",
    title: "Sort and Filter Employee Directory",
    categoryId: "tables-grids",
    component: "table",
    variant: "sort-filter",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/employees-25",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 25-row employee table with sortable column headers and a department filter dropdown.",
      dataNeeded: "None.",
      action: "Sort by \"Name\" ascending, then filter the department to \"Engineering\".",
      expectedResult: "Rows are alphabetically sorted, then only Engineering rows remain visible.",
      validationPoints: ["First visible row after sort+filter matches the alphabetically-first Engineering employee", "Row count after filter equals the seeded Engineering headcount (6)"],
      automationConcepts: ["Column-header click for sort", "Table-row locator strategies", "Filtered row-count assertion"],
    },
    validation: [{ kind: "equals", field: "visibleRowCount", expected: 6 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "TABLE-002",
    title: "Paginate and Select Rows — Orders Grid",
    categoryId: "tables-grids",
    component: "table",
    variant: "pagination-selection",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/orders-47",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A 47-row order grid paginated at 10 rows/page, with row checkboxes, a header \"select all on this page\" checkbox, Prev/Next arrow buttons, numbered page buttons, and a \"Go to page\" jump input.",
      dataNeeded: "None.",
      action: "Go to page 3 (via numbered button, Next arrow, or the jump input), select all rows on that page, then navigate to page 1 and confirm the selection count persists.",
      expectedResult: "Selection count shows 10 after \"select all\" on page 3, and remains 10 while browsing other pages via any of Prev/Next, numbered buttons, or the jump input.",
      validationPoints: ["Page indicator equals 3 after navigating", "Selected count equals 10 after select-all", "Selected count is unchanged after paging away and back", "Prev is disabled on page 1 and Next is disabled on the last page", "Entering an out-of-range page number in the jump input clamps to the nearest valid page"],
      automationConcepts: ["Pagination control interaction (arrows, numbered buttons, and direct jump-to-page)", "Selection state persisted across page changes", "Header checkbox semantics (select-all-on-page, not global)", "Boundary-disabled-button assertions"],
    },
    validation: [{ kind: "equals", field: "selectedCount", expected: 10 }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
  {
    id: "TABLE-003",
    title: "Inline Edit and Expandable Row — Invoice Line Items",
    categoryId: "tables-grids",
    component: "table",
    variant: "inline-edit-expandable",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/invoice-lines",
    difficulty: "hard",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Each invoice row expands to show its real line items, with a full \"Add line item\" form (Product, Date, Qty, Unit Price), inline quantity editing (click to edit, blur/Enter to save), a Remove (\u00d7) action per line, and a live-recalculating invoice total \u2014 exactly like a real invoicing screen.",
      dataNeeded: "String product name, a date, an integer quantity, and a decimal unit price (e.g. \"Office Chair\", 2026-03-15, qty 2, price 199.99).",
      action: "Expand \"INV-3301\", inline-edit the existing line's quantity to 5, then use the \"Add line item\" form to add \"Office Chair\", date 2026-03-15, qty 2, price 199.99, and finally remove one line using its \u00d7 button.",
      expectedResult: "Nested line items and the add-item form are visible only while expanded; the edited quantity persists as 5 and its row total recalculates; the new line appears with the exact values entered; the invoice total always reflects the current set of lines; submitting the add-item form with a missing/invalid field shows a validation error instead of adding a bad row.",
      validationPoints: ["Quantity value equals 5 after inline edit", "New line's product/date/price match exactly what was entered", "Invoice total recalculates correctly after edits, additions, and removals", "Submitting the add form with an empty product, non-positive qty/price, or missing date shows an error and does not add a row"],
      automationConcepts: ["Expand/collapse nested-row DOM assertions", "Inline-edit-then-blur/Enter pattern", "Multi-field form validation inside a nested/expandable row", "Derived-value (running total) recalculation assertion", "Add-then-remove row lifecycle testing"],
      edgeCases: ["Try adding a line with price 0 or a blank product name \u2014 both must be rejected with a visible error, not silently ignored."],
    },
    validation: [
      { kind: "equals", field: "lineQuantity", expected: 5 },
      { kind: "equals", field: "addedLineItemProduct", expected: "Office Chair" },
      { kind: "equals", field: "addedLineItemDate", expected: "2026-03-15" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 6,
    resettable: true,
    isActive: true,
  },
];
