import type { ChallengeDefinition } from "../../challenge-schema";

/** Tabs (spec category #11). All variants share the `tabs` engine component. */
export const tabsChallenges: ChallengeDefinition[] = [
  {
    id: "TABS-001",
    title: "Standard Tabs Preserving Form State",
    categoryId: "tabs",
    component: "tabs",
    variant: "state-preserving",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A customer profile has \"Details\" and \"Billing\" tabs; switching tabs must not lose unsaved input in either tab's form.",
      dataNeeded: "String, e.g. a company name.",
      action: "Type \"Globex Corp\" in the Details tab's Company field, switch to Billing, then switch back to Details.",
      expectedResult: "The Company field still shows \"Globex Corp\" after switching away and back.",
      validationPoints: ["Company field value persists across tab switches", "Only one tab panel is visible/rendered as active at a time"],
      automationConcepts: ["Tab-panel visibility assertion", "State persistence across UI navigation", "aria-selected attribute checks"],
    },
    validation: [{ kind: "equals", field: "companyName", expected: "Globex Corp" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "TABS-002",
    title: "Closable Dynamic Tabs — Open Report Workspace",
    categoryId: "tabs",
    component: "tabs",
    variant: "closable-dynamic",
    behavior: ["dynamic"],
    environment: ["none"],
    dataSource: "static/reports",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Opening a report from a list adds a new closable tab; closing the active tab activates the previous one.",
      dataNeeded: "None.",
      action: "Open \"Q3 Sales\" and \"Q3 Expenses\" as tabs, then close \"Q3 Expenses\".",
      expectedResult: "Two tabs exist after opening both; after closing the second, exactly one tab remains and it is active.",
      validationPoints: ["Tab count equals 2 after opening both reports", "Tab count equals 1 and active tab equals \"Q3 Sales\" after closing"],
      automationConcepts: ["Dynamically created/destroyed tab elements", "Active-tab-after-close focus management"],
    },
    validation: [
      { kind: "equals", field: "tabCount", expected: 1 },
      { kind: "equals", field: "activeTab", expected: "Q3 Sales" },
    ],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "TABS-003",
    title: "Disabled Tab Until Prerequisite Step",
    categoryId: "tabs",
    component: "tabs",
    variant: "disabled-until-prerequisite",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/onboarding-steps",
    difficulty: "medium",
    frameworks: ["selenium", "playwright"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An onboarding wizard has 3 tabs (Account, Company, Review); \"Review\" is disabled until required fields in \"Company\" are completed.",
      dataNeeded: "String company name.",
      action: "Try clicking \"Review\" immediately (blocked), then fill the Company name and try again.",
      expectedResult: "\"Review\" tab is unreachable while Company is incomplete, and becomes clickable once the name is filled.",
      validationPoints: ["Review tab has aria-disabled=\"true\" while incomplete", "Review tab becomes enabled and navigable after the field is filled"],
      automationConcepts: ["Disabled-tab negative assertion", "Conditional enablement across steps"],
    },
    validation: [{ kind: "equals", field: "reviewTabEnabled", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
