import type { ChallengeDefinition } from "../../challenge-schema";

/** Tooltips & Hover Elements (spec category #15). All variants share the `tooltip` engine component. */
export const tooltipsHoverChallenges: ChallengeDefinition[] = [
  {
    id: "TOOLTIP-001",
    title: "Hover Tooltip with Delay on Info Icon",
    categoryId: "tooltips-hover",
    component: "tooltip",
    variant: "hover-delayed",
    behavior: ["delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "easy",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "An info (\u24d8) icon next to \"Net Revenue\" shows an explanatory tooltip after a 400ms hover delay (not instantly).",
      dataNeeded: "None.",
      action: "Hover over the info icon and wait, then move away.",
      expectedResult: "Tooltip is absent immediately on hover, appears after ~400ms, and disappears promptly on mouse-leave.",
      validationPoints: ["Tooltip is not present at hover+0ms", "Tooltip is present at hover+500ms", "Tooltip is removed shortly after mouse-leave"],
      automationConcepts: ["Timing-aware hover assertions", "Avoiding false negatives from checking too early"],
    },
    validation: [{ kind: "truthy", field: "tooltipVisible" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 2,
    resettable: true,
    isActive: true,
  },
  {
    id: "TOOLTIP-002",
    title: "Rich HTML Tooltip with Action Button",
    categoryId: "tooltips-hover",
    component: "tooltip",
    variant: "rich-html-with-button",
    behavior: ["static"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "A user avatar's tooltip contains rich HTML (name, role, and a \"Message\" button) rather than plain text, and stays open while hovered.",
      dataNeeded: "None.",
      action: "Hover the avatar, then click \"Message\" inside the tooltip itself.",
      expectedResult: "Tooltip stays open while the cursor moves into it; clicking \"Message\" opens a compose panel.",
      validationPoints: ["Tooltip remains visible when cursor moves from the trigger into the tooltip body", "Clicking the in-tooltip button triggers its action"],
      automationConcepts: ["Interactive tooltip hit-testing", "Locating and clicking elements inside a floating/portal-rendered tooltip"],
    },
    validation: [{ kind: "equals", field: "composeOpen", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
];
