import type { ChallengeDefinition } from "../../challenge-schema";

/** Wait & Synchronization Challenges (spec category #26). All variants share the `dynamic-dom` engine component. */
export const waitSyncChallenges: ChallengeDefinition[] = [
  {
    id: "WAIT-001",
    title: "Button Becomes Clickable Only After Spinner Disappears",
    categoryId: "wait-sync",
    component: "dynamic-dom",
    variant: "button-enabled-after-spinner",
    behavior: ["delayed"],
    environment: ["none"],
    dataSource: "static/none",
    difficulty: "medium",
    frameworks: ["selenium", "playwright", "cypress"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Prepare Export\" shows a spinner for ~1.5s; the \"Download\" button exists in the DOM the whole time but only becomes enabled once the spinner is gone.",
      dataNeeded: "None.",
      action: "Click \"Prepare Export\", then click \"Download\" as soon as it becomes enabled (not before).",
      expectedResult: "Clicking Download while disabled has no effect; clicking after the spinner disappears succeeds.",
      validationPoints: ["downloadClicked is only true after the spinner-hidden state was reached", "Button remains present (not removed) throughout, only its disabled state changes"],
      automationConcepts: ["Explicit wait for element-enabled state (not just presence)", "Avoiding race conditions between visibility and interactability"],
    },
    validation: [{ kind: "equals", field: "downloadClicked", expected: true }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 3,
    resettable: true,
    isActive: true,
  },
  {
    id: "WAIT-002",
    title: "Chained API Dependency — Two Sequential Calls",
    categoryId: "wait-sync",
    component: "dynamic-dom",
    variant: "chained-api-dependency",
    behavior: ["api", "dependent", "delayed"],
    environment: ["none"],
    dataSource: "api/lab-chained",
    difficulty: "expert",
    frameworks: ["playwright", "cypress", "generic-api"],
    accessibility: "expected-accessible",
    guidance: {
      whatItDoes: "Clicking \"Get Shipment ETA\" first calls `GET /api/lab/chained/step1` (~500ms) to fetch a tracking token, then automatically calls `GET /api/lab/chained/step2` (~500ms) using that token to fetch the ETA. The ETA cannot be requested without a valid token from step 1.",
      dataNeeded: "None \u2014 the token is generated server-side.",
      action: "Click \"Get Shipment ETA\" once and wait for both chained calls to complete.",
      expectedResult: "A single click triggers two sequential network calls; the final ETA (\"3 business days\") only renders after both resolve.",
      validationPoints: ["eta equals \"3 business days\"", "step2 must not be called (or must fail) without a token produced by step1"],
      automationConcepts: ["Multi-request dependency chains", "Waiting on the final network response rather than the first", "API synchronization across sequential calls"],
    },
    validation: [{ kind: "equals", field: "eta", expected: "3 business days" }],
    mode: { deterministic: true, randomAvailable: false },
    estimatedMinutes: 4,
    resettable: true,
    isActive: true,
  },
];
